import type { PageDoc } from "../blocks";

/** Careers: the careers home and the nine pages under it. SAMPLE CONTENT: every person, figure and role is a placeholder. */
export const careersPages: PageDoc[] = [
  /* ------------------------------------------------------------------ */
  {
    href: "/careers",
    title: "Careers",
    section: "KIASA",
    summary: "Do the best work of your career, with people who take the craft seriously.",
    blocks: [
      {
        type: "hero",
        variant: "photo",
        eyebrow: "Careers",
        title: "Grow alongside people who take the craft seriously",
        lines: ["Grow alongside people", "who take the craft seriously"],
        lead: "Small senior teams, real ownership and time set aside to learn. Come and do work you will still be proud of in ten years.",
        body: [
          "KIASA is owned by the people who work in it. We design, build and run systems alongside our clients, and we hand them over in good order.",
        ],
        cta: { label: "Search for jobs", href: "/careers/search-for-jobs" },
        image: "bright-room",
      },
      {
        type: "intro",
        eyebrow: "Why KIASA",
        text: "We hire people who care how things are made. You will work in a team of five or six, close to the client and close to the code, with the time and the trust to do the job properly rather than quickly and twice.",
        body: [
          "There are no bench weeks and no anonymous staffing pools. You join a studio, you know the partners by name, and the work you do shows up in systems people rely on every day.",
          "We are independent, so nobody sells you a product to push. We choose the right tool for the client, and we expect you to tell us when we have chosen wrong.",
        ],
        cta: { label: "See what a week looks like", href: "/careers/working-here" },
      },
      {
        type: "media",
        eyebrow: "Find where you fit",
        heading: "Areas and programs",
        intro: "Five areas of work, one way of working. Start where your strengths are, and move when you are ready.",
        items: [
          { image: "design-table", eyebrow: "Career areas", title: "Engineering, design, data, delivery and advisory", text: "What each area does on a client team, and the skills we look for.", href: "/careers/career-areas", cta: "Explore" },
          { image: "young-leaves", eyebrow: "Early careers", title: "Graduate roles and internships", text: "An 18-month graduate program and paid summer internships, in six studios.", href: "/careers/early-careers", cta: "Explore" },
          { image: "laptop-notebook", eyebrow: "Learning and growth", title: "Ten learning days a year, and a budget to match", text: "Time to get better at your craft, protected in the plan of every project.", href: "/careers/learning-and-growth", cta: "Explore" },
          { image: "cafe-table", eyebrow: "Working here", title: "What a week at KIASA looks like", text: "Client days, studio days and the rituals that keep teams honest.", href: "/careers/working-here", cta: "Explore" },
        ],
      },
      {
        type: "stats",
        tone: "paper",
        eyebrow: "In numbers",
        heading: "What our people tell us",
        items: [
          { value: "87%", label: "of our people would recommend KIASA to a friend as a place to work." },
          { value: "10 days", label: "of learning time a year for everyone, written into every project plan." },
          { value: "1 in 3", label: "of our partners joined KIASA as a graduate or in their first role." },
          { value: "6", label: "people on a typical client team, from first sketch to handover." },
        ],
        source: "KIASA people survey, June 2026, and internal records. Sample figures.",
      },
      {
        type: "split",
        eyebrow: "Ownership",
        heading: "Owned by the people who work in it",
        body: [
          "After your first year, you become an owner of KIASA. There are no outside investors, so the profit we make is shared among the people who made it, and decisions are made by people who will live with them.",
          "Owners vote on new partners, see the accounts every quarter and can ask any question at the annual meeting. Most do.",
        ],
        cta: { label: "Read about our benefits", href: "/careers/benefits" },
        image: "cafe-windows",
        side: "right",
      },
      {
        type: "quote",
        text: "On my first project I shipped code in week two, and in month three I was the person the client called when something broke. Nobody hands you that kind of trust as a slogan. You get it because the team is small enough to notice what you do.",
        name: "Amara Njoroge",
        role: "Senior Engineer, Nairobi",
        image: "leaf-drops",
      },
      {
        type: "features",
        eyebrow: "Benefits",
        heading: "The practical details, looked after",
        intro: "The same principles in every studio, adjusted to local law and custom.",
        items: [
          { title: "Pay you can see", text: "Salary bands for every level are published inside the firm. You will know where you sit and why.", pattern: "pulse", link: { label: "Benefits", href: "/careers/benefits" } },
          { title: "A share of what we make", text: "Every owner receives an equal part of the annual profit share, whatever their level.", pattern: "rings", link: { label: "Benefits", href: "/careers/benefits" } },
          { title: "Time away that counts", text: "At least 25 days of paid leave plus public holidays, and a four-week sabbatical every five years.", pattern: "waves", link: { label: "Benefits", href: "/careers/benefits" } },
          { title: "Twenty weeks for new parents", text: "Full pay for every new parent, however your family arrives.", pattern: "branches", link: { label: "Benefits", href: "/careers/benefits" } },
          { title: "Health, properly covered", text: "Private health cover where the public system leaves gaps, and confidential counseling for you and your household.", pattern: "veins", link: { label: "Benefits", href: "/careers/benefits" } },
          { title: "Learning on the clock", text: "Ten learning days a year and a personal budget for courses, books and conferences.", pattern: "strata", link: { label: "Learning and growth", href: "/careers/learning-and-growth" } },
        ],
      },
      {
        type: "news",
        heading: "News from KIASA",
        intro: "What the firm has been doing lately.",
        items: [
          { date: "2026-09-29", title: "KIASA launches Canopy, a managed platform team for mid-size enterprises", href: "/newsroom/kiasa-launches-canopy", kind: "Announcement" },
          { date: "2026-08-12", title: "KIASA appoints Daniel Okafor as Chief Delivery Officer", href: "/newsroom/chief-delivery-officer", kind: "News" },
          { date: "2026-07-30", title: "KIASA publishes its first sustainability report", href: "/newsroom/first-sustainability-report", kind: "News" },
          { date: "2026-07-16", title: "KIASA opens a second engineering studio", href: "/newsroom/second-engineering-studio", kind: "News" },
        ],
        cta: { label: "Visit the newsroom", href: "/newsroom" },
      },
      {
        type: "cta",
        heading: "Find the role that fits",
        text: "Every open role in every studio, in one list. If nothing fits today, read how we hire and come back soon.",
        cta: { label: "Search for jobs", href: "/careers/search-for-jobs" },
        secondary: { label: "How we hire", href: "/careers/hiring-journey" },
        image: "hiker-valley",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/careers/search-for-jobs",
    title: "Search for Jobs",
    section: "Find a job",
    summary: "Every open role, in one place.",
    blocks: [
      {
        type: "hero",
        variant: "plain",
        eyebrow: "Find a job",
        title: "Search for jobs",
        lead: "Every open role, in every studio, in one place. Filter by area, studio or kind of role, and apply directly to the team that is hiring.",
        pattern: "branches",
      },
      {
        type: "jobs",
        heading: "Open roles",
        intro: "24 roles across engineering, design, data, delivery and advisory. Remote roles are open to anyone living within the region named.",
        jobs: [
          { title: "Senior Platform Engineer", area: "Engineering", location: "Amsterdam, Netherlands", kind: "Full time", posted: "2026-09-29", summary: "Build the internal platforms our clients' teams deploy on, from the network up to the paved path." },
          { title: "Delivery Lead", area: "Delivery", location: "Austin, United States", kind: "Full time", posted: "2026-09-29", summary: "Lead a team of six through a core platform replacement for a regional insurer, from plan to handover." },
          { title: "Backend Engineer (Java and Kotlin)", area: "Engineering", location: "Lisbon, Portugal", kind: "Full time", posted: "2026-09-28", summary: "Move claims and policy logic off an aging core, one product line at a time, with tests first." },
          { title: "Data Engineer", area: "Data", location: "Amsterdam, Netherlands", kind: "Full time", posted: "2026-09-27", summary: "Design pipelines that move meter and grid data once, correctly, and keep a record of every change." },
          { title: "Frontend Engineer", area: "Engineering", location: "Remote (Europe)", kind: "Full time", posted: "2026-09-26", summary: "Build accessible, fast interfaces in TypeScript for public services and patient-facing products." },
          { title: "Product Designer", area: "Design", location: "Lisbon, Portugal", kind: "Full time", posted: "2026-09-25", summary: "Shape products with engineers in the same team, from the first research session to steady release." },
          { title: "Site Reliability Engineer, KIASA Canopy", area: "Engineering", location: "Toronto, Canada", kind: "Full time", posted: "2026-09-24", summary: "Keep client platforms running and secure, and write the monthly report a finance director can read." },
          { title: "Machine Learning Engineer", area: "Data", location: "Austin, United States", kind: "Full time", posted: "2026-09-23", summary: "Put models to work on back-office tasks with measurable savings, and keep them honest in production." },
          { title: "Security Engineer", area: "Engineering", location: "London, United Kingdom", kind: "Full time", posted: "2026-09-22", summary: "Threat model new systems before they are built, and test running ones the way an attacker would." },
          { title: "Quality Engineer", area: "Engineering", location: "Singapore", kind: "Full time", posted: "2026-09-21", summary: "Build testing into delivery pipelines so that a release on a Tuesday afternoon is unremarkable." },
          { title: "Engagement Manager", area: "Delivery", location: "Singapore", kind: "Full time", posted: "2026-09-19", summary: "Own the relationship and the plan for two client programs in logistics and retail." },
          { title: "Integration Engineer", area: "Engineering", location: "Nairobi, Kenya", kind: "Full time", posted: "2026-09-18", summary: "Connect payment, billing and customer systems through well-documented APIs that outlast the project." },
          { title: "Technology Strategy Principal", area: "Advisory", location: "London, United Kingdom", kind: "Full time", posted: "2026-09-17", summary: "Help leadership teams make clear technology choices, costed and sequenced, before anything is built." },
          { title: "Service Designer", area: "Design", location: "London, United Kingdom", kind: "Full time", posted: "2026-09-15", summary: "Map how a service really works, front stage and back, and redesign it with the people who run it." },
          { title: "Delivery Manager, KIASA Canopy", area: "Delivery", location: "Nairobi, Kenya", kind: "Full time", posted: "2026-09-14", summary: "Run the standing team behind several managed platforms, with clear priorities and no surprises." },
          { title: "Analytics Engineer", area: "Data", location: "Remote (Asia Pacific)", kind: "Full time", posted: "2026-09-12", summary: "Model clinic and scheduling data into tables that people trust and dashboards they actually use." },
          { title: "User Researcher", area: "Design", location: "Melbourne, Australia", kind: "Full time", posted: "2026-09-10", summary: "Plan and run research with staff and customers, and turn what you hear into decisions the team can act on." },
          { title: "Technology Due Diligence Associate", area: "Advisory", location: "Amsterdam, Netherlands", kind: "Full time", posted: "2026-09-09", summary: "Review technology estates for investors in two to four weeks, and write findings that hold up." },
          { title: "Accessibility Specialist", area: "Design", location: "Remote (North America)", kind: "Part time", posted: "2026-09-08", summary: "Audit and coach across our product teams, three days a week, so accessibility is built in from the start." },
          { title: "Data Platform Lead", area: "Data", location: "Toronto, Canada", kind: "Full time", posted: "2026-09-04", summary: "Set the direction for a utility's data platform and lead the engineers who build it." },
          { title: "Enterprise Architect", area: "Advisory", location: "Melbourne, Australia", kind: "Full time", posted: "2026-09-03", summary: "Design the target architecture for ERP and core platform programs, and stay with them through delivery." },
          { title: "Summer Intern, Experience Design (2027)", area: "Design", location: "Toronto, Canada", kind: "Internship", posted: "2026-09-02", summary: "Ten paid weeks on a real client team, with a mentor and a piece of work to show at the end." },
          { title: "Graduate Software Engineer (2027 intake)", area: "Engineering", location: "Lisbon, Portugal", kind: "Graduate", posted: "2026-09-01", summary: "An 18-month program of three client placements, starting September 2027." },
          { title: "Graduate Data Analyst (2027 intake)", area: "Data", location: "Remote (Europe)", kind: "Graduate", posted: "2026-09-01", summary: "Join a data team on client work from week one, with structured training alongside." },
        ],
      },
      {
        type: "features",
        tone: "paper",
        eyebrow: "Not sure where you fit?",
        heading: "Start with the work, not the job title",
        items: [
          { title: "Career areas", text: "What engineers, designers, data people, delivery leads and advisors do on a KIASA team.", pattern: "branches", link: { label: "Explore career areas", href: "/careers/career-areas" } },
          { title: "Early careers", text: "Graduate roles and internships, with training built around real client work.", pattern: "strata", link: { label: "Explore early careers", href: "/careers/early-careers" } },
          { title: "Working here", text: "What a week looks like, from Monday planning to Friday demos.", pattern: "orbit", link: { label: "See a week at KIASA", href: "/careers/working-here" } },
        ],
      },
      {
        type: "steps",
        eyebrow: "After you apply",
        heading: "What happens next",
        intro: "Four conversations at most, and a reply at every step.",
        items: [
          { title: "We read every application", text: "A person on the hiring team reads it, not a filter. You hear back within ten working days." },
          { title: "A first conversation", text: "Thirty minutes with someone from the team you would join, about the work and what you want from it." },
          { title: "A working session", text: "A paired exercise on a realistic problem. No trick questions and no unpaid take-home projects." },
          { title: "Meet the partners", text: "A conversation about values and ways of working, then an offer or honest feedback within a week." },
        ],
      },
      {
        type: "accordion",
        heading: "Questions about applying",
        items: [
          { title: "Can I apply for more than one role?", body: ["Yes, up to three at a time. Tell us in your note which matters most to you, and we will route your application to that team first."] },
          { title: "Do you sponsor work visas?", body: ["For most full-time roles, yes, where local rules allow. Each role says so if it cannot. Ask us early and we will be clear about the timeline."] },
          { title: "What does remote mean at KIASA?", body: ["Remote roles are open to anyone living within the region named. You will be attached to the nearest studio and meet your team in person at least once a quarter, with travel paid."] },
          { title: "I need an adjustment for the interview. Who do I tell?", body: ["Tell the recruiter named in your first email, or write to careers@kiasa.tech. We will arrange it without asking for a reason, and it will not affect how we assess you."] },
          { title: "Nothing fits right now. What should I do?", body: ["New roles are posted most weeks. Read how we hire in the meantime, and come back to this page. We do not keep CVs on file without asking."], link: { label: "Read about the hiring journey", href: "/careers/hiring-journey" } },
        ],
      },
      {
        type: "quote",
        text: "I applied on a Sunday night and had a reply from a real person by Wednesday. The working session felt like a normal day on the team, which is exactly what it turned out to be.",
        name: "Mateo Alvarez",
        role: "Software Engineer, Austin",
        image: "escalators",
      },
      {
        type: "cta",
        heading: "Ready when you are",
        text: "Read what we look for in an interview and how to prepare, then send us your application.",
        cta: { label: "Read the interview tips", href: "/careers/interview-tips" },
        secondary: { label: "Write to careers@kiasa.tech", href: "mailto:careers@kiasa.tech" },
        image: "rail-tracks",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/careers/career-areas",
    title: "Career Areas",
    section: "Find a job",
    summary: "Engineering, design, data, delivery and advisory.",
    blocks: [
      {
        type: "hero",
        variant: "split",
        eyebrow: "Career areas",
        title: "Five crafts, one team",
        lead: "Engineering, design, data, delivery and advisory. Every client team mixes them, and each is treated as a craft worth getting good at.",
        cta: { label: "See open roles", href: "/careers/search-for-jobs" },
        image: "workbench",
      },
      {
        type: "intro",
        text: "We do not split thinking from doing. The people who advise a client on what to build sit beside the people who build it, and the people who build it stay to run it. Whatever your area, you will see your work through.",
        body: [
          "A typical team has three or four engineers, a designer, someone from data and a delivery lead, with an advisory partner close by.",
          "Titles are short and levels are published. What changes as you grow is the size of the problem you are trusted with.",
        ],
      },
      {
        type: "accordion",
        eyebrow: "The areas",
        heading: "What each area does on a client team",
        items: [
          {
            title: "Engineering",
            body: [
              "Platform, backend, frontend, security, integration and quality engineers. You write production code, review it, test it and run it, and you are expected to have an opinion about how it should be built.",
              "Our engineers work across modernization, cloud platforms and product builds, and many spend time on KIASA Canopy, keeping client platforms running.",
            ],
            stat: { value: "48%", label: "of our people work in engineering." },
            link: { label: "Engineering roles", href: "/careers/search-for-jobs" },
          },
          {
            title: "Design",
            body: [
              "Product designers, service designers, researchers and accessibility specialists. You talk to the people who will use what we build, and you stay in the team while it is built, not just until the handoff.",
            ],
            stat: { value: "14%", label: "of our people work in design and research." },
            link: { label: "Design roles", href: "/careers/search-for-jobs" },
          },
          {
            title: "Data",
            body: [
              "Data engineers, analytics engineers, data scientists and machine learning engineers. You build data platforms people trust, and put models to work only where the numbers say they help.",
            ],
            stat: { value: "16%", label: "of our people work in data and AI." },
            link: { label: "Data roles", href: "/careers/search-for-jobs" },
          },
          {
            title: "Delivery",
            body: [
              "Delivery leads, engagement managers and delivery managers. You keep the plan honest, the client informed and the team free to work. You know the code well enough to ask good questions about it.",
            ],
            stat: { value: "12%", label: "of our people work in delivery." },
            link: { label: "Delivery roles", href: "/careers/search-for-jobs" },
          },
          {
            title: "Advisory",
            body: [
              "Strategists, architects and due diligence specialists. You help clients decide what to build, in what order and at what cost, and you stay accountable for that advice once the building starts.",
            ],
            stat: { value: "10%", label: "of our people work in advisory." },
            link: { label: "Advisory roles", href: "/careers/search-for-jobs" },
          },
        ],
      },
      {
        type: "split",
        eyebrow: "How teams form",
        heading: "Mixed teams, from the first week",
        body: [
          "Each project starts with a team of five or six drawn from several areas. The designer hears the engineering trade-offs; the engineers hear what the research found. Nobody throws work over a wall, because there is no wall.",
          "Teams are formed in the studio, so you will usually know your colleagues before the project starts.",
        ],
        image: "desk-flatlay",
        side: "left",
      },
      {
        type: "split",
        eyebrow: "Changing course",
        heading: "Moving between areas is normal",
        body: [
          "Some of our best data engineers started as backend engineers. Some of our delivery leads started as designers. If you want to move, tell your career coach. We will find you a project where you can try the new work with support around you.",
          "About one in ten of our people change area in a given year.",
        ],
        cta: { label: "Learning and growth", href: "/careers/learning-and-growth" },
        image: "train-carriage",
        side: "right",
      },
      {
        type: "stats",
        tone: "paper",
        heading: "The areas, by the numbers",
        items: [
          { value: "5", label: "career areas, each with published levels and pay bands." },
          { value: "1 in 10", label: "of our people move to a different area each year." },
          { value: "6", label: "people on a typical team, drawn from at least three areas." },
        ],
        source: "KIASA internal records, 2025. Sample figures.",
      },
      {
        type: "quote",
        text: "I joined as a backend engineer and spent two years being curious about why our pipelines kept breaking. Now I lead the data work for the same client. Nobody made me apply for anything. I said what I wanted, and the next project gave me room to try it.",
        name: "Joost van Leeuwen",
        role: "Data Engineer, Amsterdam",
        image: "bamboo",
      },
      {
        type: "cta",
        heading: "Find your area, then find your role",
        text: "Open roles in all five areas, across our studios.",
        cta: { label: "Search for jobs", href: "/careers/search-for-jobs" },
        secondary: { label: "Early careers", href: "/careers/early-careers" },
        image: "forest-path",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/careers/early-careers",
    title: "Early Careers",
    section: "Find a job",
    summary: "Graduate roles and internships.",
    blocks: [
      {
        type: "hero",
        variant: "split",
        eyebrow: "Early careers",
        title: "Start on real work, with people who teach",
        lead: "Graduate roles and paid internships on client teams from the first week. Applications for the 2027 intake are open now.",
        cta: { label: "See graduate and intern roles", href: "/careers/search-for-jobs" },
        image: "college-lawn",
      },
      {
        type: "intro",
        text: "You will not spend your first year on training slides. You will join a client team, write code or run research that ships, and have a mentor who has set time aside for you every week. We hire graduates because we want them to stay and become partners.",
        body: [
          "We look for curiosity and care, not a particular degree. Some of our graduates studied computer science; others studied history, music or nursing.",
        ],
      },
      {
        type: "media",
        eyebrow: "Programs",
        heading: "Three ways to start",
        items: [
          { image: "laptop-typing", eyebrow: "Graduate program", title: "Eighteen months, three placements", text: "Three six-month client placements in engineering, design or data, starting September 2027.", href: "/careers/search-for-jobs", cta: "See graduate roles" },
          { image: "camera-hands", eyebrow: "Summer internship", title: "Ten paid weeks on a client team", text: "A real piece of work, a mentor, and a short presentation to the partners at the end.", href: "/careers/search-for-jobs", cta: "See internships" },
          { image: "desk-white", eyebrow: "Apprenticeship", title: "Learn and earn, over two years", text: "A software engineering apprenticeship in London and Melbourne, with study days paid and protected.", href: "/careers/search-for-jobs", cta: "See open roles" },
        ],
      },
      {
        type: "steps",
        eyebrow: "Your first year",
        heading: "What the first year looks like",
        items: [
          { title: "Two weeks in the studio", text: "Meet your cohort, set up your tools and learn how we work, with one small piece of real code or research to finish." },
          { title: "Your first placement", text: "Join a client team of five or six. Your mentor is on the same team and you meet one to one every week." },
          { title: "First review", text: "At three months, a written review from your team about what went well and what to work on next." },
          { title: "Second placement", text: "A different client, industry or area, chosen with you, so you can find where you do your best work." },
          { title: "One year in", text: "You become an owner of KIASA, with a share of the profit and a vote at the annual meeting." },
        ],
      },
      {
        type: "stats",
        tone: "paper",
        heading: "Our graduates, by the numbers",
        items: [
          { value: "42", label: "graduates and interns joined KIASA across six studios in 2025." },
          { value: "91%", label: "of our 2023 graduates are still with KIASA today." },
          { value: "1 in 3", label: "of our partners joined as a graduate or in their first role." },
        ],
        source: "KIASA internal records, September 2026. Sample figures.",
      },
      {
        type: "quote",
        text: "In my second placement I ran the usability sessions for a clinic booking system, and three weeks later the nurses were using the version we had changed. I had expected to be watching from the back of the room for a year.",
        name: "Ines Duarte",
        role: "Graduate Product Designer, Lisbon",
        image: "leaf-drop",
      },
      {
        type: "accordion",
        heading: "Questions from graduates",
        items: [
          { title: "Do I need a computer science degree?", body: ["No. For engineering roles we ask you to show us something you have built, from coursework or on your own. For design and data roles, a portfolio or a short write-up of a project is enough."] },
          { title: "When do the programs start?", body: ["The graduate program starts each September. Summer internships run for ten weeks from late June. Apprenticeships start in September and February."] },
          { title: "Are internships paid?", body: ["Always. Interns are paid at the same rate as first-year graduates, and we cover travel to the studio."] },
          { title: "Can I choose my studio?", body: ["Yes. Tell us your first and second choice. Graduate roles are open in Lisbon, Amsterdam, London, Toronto, Austin and Melbourne this year."] },
        ],
      },
      {
        type: "cta",
        heading: "Applications for 2027 are open",
        text: "Read how we hire, then apply for the program that suits you.",
        cta: { label: "Search graduate roles", href: "/careers/search-for-jobs" },
        secondary: { label: "Hiring journey", href: "/careers/hiring-journey" },
        image: "wheat",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/careers/working-here",
    title: "Working Here",
    section: "Life at KIASA",
    summary: "What a week at KIASA looks like.",
    blocks: [
      {
        type: "hero",
        variant: "split",
        eyebrow: "Life at KIASA",
        title: "A week at KIASA",
        lead: "Client work most days, a day in the studio, and a rhythm that leaves room for thinking. Here is what an ordinary week looks like.",
        cta: { label: "See open roles", href: "/careers/search-for-jobs" },
        image: "desk-window",
      },
      {
        type: "intro",
        text: "We work at a steady pace on purpose. Teams that are not exhausted make fewer mistakes, write clearer code and notice when something is wrong. The habits below are how we keep it that way, in every studio and on every client.",
      },
      {
        type: "steps",
        eyebrow: "An ordinary week",
        heading: "Monday to Friday",
        items: [
          { title: "Monday: plan", text: "The team agrees what it will finish this week, with the client in the room. Anything that does not fit is written down, not squeezed in." },
          { title: "Tuesday: build", text: "Long blocks of focused work. Meetings are kept to the morning, and afternoons are quiet by default." },
          { title: "Wednesday: studio day", text: "Most people work from the studio. Critiques, pairing across teams, lunch together and a short talk from someone in the firm." },
          { title: "Thursday: release", text: "Changes go to production in daylight, with the people who wrote them watching. Releases are routine, not events." },
          { title: "Friday: show and reflect", text: "A demo for the client, a short retrospective, and the afternoon set aside for learning time or tidying up." },
        ],
      },
      {
        type: "split",
        eyebrow: "Where we work",
        heading: "Studios, not offices",
        body: [
          "Our studios are small, between twenty and ninety people, and built for working together: long tables, quiet rooms and walls you can write on. Most people come in two or three days a week, and nobody counts.",
          "You will also spend time with clients on site, especially at the start of a project. We plan travel weeks ahead and keep overnight trips to a minimum.",
        ],
        cta: { label: "Find our studios", href: "/about/locations" },
        image: "street-crowd",
        side: "left",
      },
      {
        type: "split",
        eyebrow: "How we decide",
        heading: "Written down, and open to everyone",
        body: [
          "Decisions that matter are written up in a short note anyone can read and comment on. The accounts are shared with every owner each quarter. If you want to know why something is the way it is, you can find out.",
          "Partners keep open hours every week. Ask them anything.",
        ],
        cta: { label: "How we work with clients", href: "/about/how-we-work" },
        image: "keyboard-mug",
        side: "right",
      },
      {
        type: "stats",
        tone: "paper",
        heading: "A sustainable pace, measured",
        items: [
          { value: "38 hours", label: "is our standard working week, and we track overtime so it stays rare." },
          { value: "2 to 3", label: "days a week in the studio for most people, chosen by the team." },
          { value: "4%", label: "of weeks last year included work outside normal hours, down from 7% in 2024." },
        ],
        source: "KIASA time records, 2025. Sample figures.",
      },
      {
        type: "quote",
        text: "The Thursday release used to make me nervous at other firms. Here it is so routine that we bring cake only when nothing happens, which is most weeks.",
        name: "Noah Bergström",
        role: "Quality Engineer, Amsterdam",
        image: "evening-street",
      },
      {
        type: "features",
        heading: "The habits that hold it together",
        numbered: true,
        items: [
          { title: "No hero work", text: "If a weekend fix is needed, we ask why and fix the cause. One person carrying a system is a risk, not a virtue." },
          { title: "Handover from week one", text: "We write things down as we go, so the client's own team can run what we build." },
          { title: "Critique, kindly", text: "Work is reviewed in the open, and feedback is about the work, given with care and taken without fear." },
          { title: "Quiet afternoons", text: "Meetings in the morning where possible, so the rest of the day is for deep work." },
          { title: "Paid time to think", text: "Friday afternoons and ten learning days a year are protected in every project plan." },
          { title: "Small teams", text: "Five or six people, so everyone knows what everyone else is doing." },
        ],
      },
      {
        type: "cta",
        heading: "Like the sound of the week?",
        text: "Every open role, in every studio.",
        cta: { label: "Search for jobs", href: "/careers/search-for-jobs" },
        secondary: { label: "Benefits", href: "/careers/benefits" },
        image: "dusk-city",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/careers/benefits",
    title: "Benefits",
    section: "Life at KIASA",
    summary: "Pay, leave, health and the practical details.",
    blocks: [
      {
        type: "hero",
        variant: "split",
        eyebrow: "Life at KIASA",
        title: "Pay, leave, health and the practical details",
        lead: "The same principles in every studio, adjusted to local law and custom. Here is what you can expect, written plainly.",
        cta: { label: "See open roles", href: "/careers/search-for-jobs" },
        image: "lake-figure",
      },
      {
        type: "intro",
        text: "Good benefits should be easy to understand and hard to lose. Ours are the same at every level, from graduate to partner, and they start on your first day, except ownership, which starts after your first year.",
        body: [
          "The details below are a summary. Your offer letter sets out exactly what applies in your country, and the people team will walk you through it before you sign.",
        ],
      },
      {
        type: "features",
        eyebrow: "At a glance",
        heading: "What every KIASA person receives",
        items: [
          { title: "Published pay bands", text: "Every level has a salary band, visible to everyone inside the firm and reviewed each year against the market.", pattern: "pulse" },
          { title: "Ownership and profit share", text: "After one year you become an owner. The annual profit share is split equally among owners, whatever their level.", pattern: "rings" },
          { title: "At least 25 days of leave", text: "Plus public holidays, and a four-week paid sabbatical every five years.", pattern: "waves" },
          { title: "Twenty weeks for new parents", text: "At full pay, for every parent, however your family arrives, with a phased return if you want one.", pattern: "branches" },
          { title: "Health and wellbeing", text: "Private health cover where the public system leaves gaps, and confidential counseling for you and your household.", pattern: "veins" },
          { title: "Learning budget", text: "Ten learning days a year and $2,000 or the local equivalent for courses, books and conferences.", pattern: "strata" },
        ],
      },
      {
        type: "accordion",
        heading: "The details, by topic",
        items: [
          {
            title: "Pay",
            body: [
              "Each of our seven levels has a published salary band in each country. Your offer names your level, where you sit in its band, and why.",
              "Pay is reviewed every April. Movement within a band follows your review; moving up a level comes with a new band.",
            ],
            stat: { value: "7", label: "levels, each with a published band." },
          },
          {
            title: "Ownership",
            body: [
              "KIASA is owned by the people who work in it. After one year, every permanent employee becomes an owner at no cost to them.",
              "Owners share the annual profit equally, see the accounts each quarter and vote on new partners at the annual meeting.",
            ],
            stat: { value: "100%", label: "of KIASA is owned by the people who work in it." },
          },
          {
            title: "Leave",
            body: [
              "At least 25 days of paid leave a year, plus public holidays, and more where local law or custom gives more.",
              "After five years, a paid sabbatical of four weeks, to be used within the following two years. Many people add it to their annual leave.",
            ],
            stat: { value: "4 weeks", label: "of paid sabbatical every five years." },
          },
          {
            title: "Family",
            body: [
              "Twenty weeks of leave at full pay for every new parent, through birth, adoption or surrogacy, and a phased return over four weeks if you want it.",
              "Ten days of paid leave a year for caring for a family member, separate from your annual leave.",
            ],
            stat: { value: "20 weeks", label: "at full pay for every new parent." },
          },
          {
            title: "Health",
            body: [
              "Private health cover for you and your dependents where the public system leaves gaps, chosen country by country.",
              "Confidential counseling for you and anyone in your household, up to eight sessions a year, with no need to tell anyone at KIASA.",
            ],
          },
          {
            title: "Working arrangements",
            body: [
              "Most people come to the studio two or three days a week. Part-time and compressed hours are available in every role after your first three months, by agreement with your team.",
              "We pay for a proper desk, chair and screen at home, and the internet connection that goes with them.",
            ],
          },
        ],
      },
      {
        type: "split",
        eyebrow: "Why it is this way",
        heading: "Benefits chosen by the people who use them",
        body: [
          "Because KIASA is owned by its people, benefits are decided by them too. Every two years the owners vote on one change. The twenty weeks of parental leave came from that vote in 2024; the caring leave came from the one before.",
        ],
        cta: { label: "Who we are", href: "/about" },
        image: "orange-chair",
        side: "left",
      },
      {
        type: "stats",
        tone: "paper",
        heading: "Benefits people use",
        items: [
          { value: "94%", label: "of new parents at KIASA took their full twenty weeks in 2025." },
          { value: "23 days", label: "of leave taken on average last year, and we chase people who take too few." },
          { value: "88%", label: "of our people say the benefits are clear and fair." },
        ],
        source: "KIASA people survey, June 2026, and internal records. Sample figures.",
      },
      {
        type: "quote",
        text: "I took the full twenty weeks with both of my children. Nobody asked when I was coming back, and my project lead had the handover planned before I asked.",
        name: "Kwame Mensah",
        role: "Platform Engineer, London",
        image: "rocky-coast",
      },
      {
        type: "cta",
        heading: "Questions about the details?",
        text: "Ask the recruiter named in your first email, or write to the people team at any time.",
        cta: { label: "Search for jobs", href: "/careers/search-for-jobs" },
        secondary: { label: "Write to careers@kiasa.tech", href: "mailto:careers@kiasa.tech" },
        image: "open-sea",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/careers/learning-and-growth",
    title: "Learning and Growth",
    section: "Life at KIASA",
    summary: "Time and budget set aside for getting better at your craft.",
    blocks: [
      {
        type: "hero",
        variant: "split",
        eyebrow: "Life at KIASA",
        title: "Time set aside for getting better",
        lead: "Ten learning days a year, a personal budget and a coach who is not your manager. Growth is planned into the work, not squeezed around it.",
        cta: { label: "See open roles", href: "/careers/search-for-jobs" },
        image: "typewriter",
      },
      {
        type: "intro",
        text: "The craft keeps changing, and so must we. Learning time is written into every project plan before the client sees it, so nobody has to choose between a deadline and a course. What you learn comes back to the team, and often to the client.",
        body: [
          "We publish what each level expects, so you can see what the next step looks like and ask for the work that gets you there.",
        ],
      },
      {
        type: "stats",
        tone: "paper",
        heading: "Learning, measured",
        items: [
          { value: "10 days", label: "of learning time a year for everyone, written into every project plan." },
          { value: "$2,000", label: "or the local equivalent each year for courses, books and conferences." },
          { value: "9.4 days", label: "of learning time used on average in 2025, out of ten." },
          { value: "31%", label: "of our open senior roles were filled from inside KIASA last year." },
        ],
        source: "KIASA internal records, 2025. Sample figures.",
      },
      {
        type: "features",
        eyebrow: "How we learn",
        heading: "Six ways to grow at KIASA",
        items: [
          { title: "A coach, not a manager", text: "Everyone has a career coach outside their project who meets them monthly and speaks up for them at review time.", pattern: "orbit" },
          { title: "Learning days", text: "Ten a year, booked like leave and protected in the plan. Use them for a course, a side project or a study group.", pattern: "strata" },
          { title: "Guilds", text: "Groups by craft across all studios: platform, security, design research, data, delivery. They meet every two weeks.", pattern: "matrix" },
          { title: "Pairing across teams", text: "Studio days pair you with someone from another project, so good habits travel.", pattern: "branches" },
          { title: "Teaching counts", text: "Running a session, writing a guide or mentoring a graduate counts toward your next level.", pattern: "veins" },
          { title: "A studio exchange", text: "After two years, spend up to six months working from another KIASA studio.", pattern: "contours" },
        ],
      },
      {
        type: "steps",
        eyebrow: "How careers grow",
        heading: "What changes as you move up",
        intro: "Seven levels, each with a published description. The difference between them is scope, not hours.",
        items: [
          { title: "Learning the craft", text: "Graduates and associates: you do good work on a well-defined part of the system, with support close by." },
          { title: "Owning a part", text: "Engineers, designers and analysts: you own a part of the system or service from start to finish." },
          { title: "Shaping the work", text: "Senior and lead roles: you shape how the team builds, and you help others grow." },
          { title: "Owning the outcome", text: "Principals: you are accountable for what a client gets from a whole program." },
          { title: "Owning the firm", text: "Partners: you are responsible for clients, for people and for KIASA itself." },
        ],
      },
      {
        type: "split",
        eyebrow: "Reviews",
        heading: "Reviews written by the people you work with",
        body: [
          "Twice a year, three or four colleagues write a short review of your work. Your coach brings it together, and you discuss it before anything is decided. There are no rankings and no quotas.",
          "Promotion follows when you are already doing the work of the next level, and the reviews say so.",
        ],
        image: "forest-canopy",
        side: "right",
      },
      {
        type: "quote",
        text: "I used my learning days to study accessibility law, then taught a session on it to the design guild. A year later I was leading the accessibility work on a public sector program. The path was visible the whole time.",
        name: "Priya Raghavan",
        role: "Design Lead, Singapore",
        image: "waterfall",
      },
      {
        type: "cta",
        heading: "Come and get better at what you do",
        text: "Every role at KIASA comes with the same time and budget for learning.",
        cta: { label: "Search for jobs", href: "/careers/search-for-jobs" },
        secondary: { label: "Career areas", href: "/careers/career-areas" },
        image: "mountain-lake",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/careers/careers-blog",
    title: "Careers Blog",
    section: "Life at KIASA",
    summary: "Stories from the people who work here.",
    blocks: [
      {
        type: "hero",
        variant: "split",
        eyebrow: "Careers blog",
        title: "Stories from the people who work here",
        lead: "What the work is really like, written by the people doing it. No ghostwriters, and no stock smiles.",
        cta: { label: "See open roles", href: "/careers/search-for-jobs" },
        image: "desk-laptop",
      },
      {
        type: "intro",
        eyebrow: "Featured story",
        heading: "Handing over a system I loved",
        text: "Amara Njoroge spent two years on the platform that lets Varda Energy read two million meters. Then her job was to make herself unnecessary. She writes about what that taught her about engineering, and about letting go.",
      },
      {
        type: "prose",
        aside: {
          heading: "In brief",
          points: [
            "Amara Njoroge, Senior Engineer in Nairobi, on the last six months of a two-year project.",
            "Handover started in the first week, but the real work was in the final quarter.",
            "Three habits made the difference: pairing, writing runbooks together and stepping back on purpose.",
            "September 18, 2026. 6 minute read.",
          ],
        },
        items: [
          { p: "The first time I was paged on the Varda Energy platform, it was three in the morning and a batch of meter readings had arrived twice. I fixed it, wrote it up and went back to sleep feeling useful. Eighteen months later, the same alert fired, and I slept through it. Someone on Varda's own team fixed it in eleven minutes. That was the best night of the project." },
          { h: "Planning to leave from the first week" },
          { p: "At KIASA we say a system is finished when the people who run it no longer need us. I had heard it at my interview and thought it was a nice line. On Varda it was a plan, with dates. In week one we named the client engineers who would own each part of the platform, and they joined our standups from the start." },
          { p: "For the first year, that was mostly a formality. We were building quickly and they were watching. The real handover came in the last six months, and it was harder than any of the engineering." },
          { figure: "city-overlook", caption: "Nairobi, where much of the Varda Energy platform was built and handed over." },
          { h: "What actually worked" },
          {
            list: [
              "Pairing on every incident, with the client engineer at the keyboard and me beside them.",
              "Writing the runbooks together, in their words, so they would read them at three in the morning.",
              "Stepping back on purpose: one week a month when no KIASA person was on call at all.",
              "Saying out loud what I did not know, so they could see it was normal not to know everything.",
            ],
          },
          { stat: "11 minutes", label: "to resolve the duplicate readings alert, by Varda's own team, in the final month." },
          { h: "The hard part" },
          { p: "The hardest thing was not technical. It was watching someone take twice as long as I would have, and saying nothing. Every time I took the keyboard back, I taught them that they still needed me. My delivery lead, Sienna Clarke, put it simply." },
          { quote: "The goal is not that the fix is fast. It is that the fix is theirs.", by: "Sienna Clarke, Delivery Lead, Melbourne" },
          { h: "What I took with me" },
          { p: "I write differently now. Every piece of code I leave behind, I imagine being read by someone tired, at night, who has never met me. I name things more plainly. I leave more comments about why and fewer about what." },
          { p: "I am on a new project now, with a new client and a new set of names written down in week one. I still check the Varda dashboards sometimes, out of habit. Everything is green, and none of it is mine any more. That is the point." },
        ],
      },
      {
        type: "quote",
        text: "We write these posts ourselves, about the work as it really is. If a story would only make sense with the hard parts cut out, we do not publish it.",
        name: "Farah Haddad",
        role: "Head of Talent, London",
        image: "leaf-dew",
      },
      {
        type: "cards",
        eyebrow: "More from our people",
        heading: "Read on",
        items: [
          { kind: "Client story", title: "Varda Energy reads two million meters without a mainframe", summary: "The project behind this month's story, told by the people who run the platform today.", href: "/client-stories/varda-energy", art: "fog-forest" },
          { kind: "Life at KIASA", title: "A week at KIASA, from Monday planning to Friday demos", summary: "The rhythm behind the work, and the habits that keep it sustainable.", href: "/careers/working-here", art: "branches", surface: "paper" },
          { kind: "Learning and growth", title: "Ten learning days a year, and what people do with them", summary: "Time and budget set aside for getting better at your craft.", href: "/careers/learning-and-growth", art: "skyline-bench" },
          { kind: "Early careers", title: "What a graduate's first year looks like", summary: "Three placements, a weekly mentor and real work from the first fortnight.", href: "/careers/early-careers", art: "orbit", surface: "night" },
        ],
      },
      {
        type: "news",
        heading: "Recent stories",
        intro: "Earlier posts from the careers blog, filed with the pages they are about.",
        items: [
          { date: "2026-09-18", title: "Handing over a system I loved", href: "/careers/careers-blog", kind: "Engineering" },
          { date: "2026-09-04", title: "How we spent our learning days this year, in numbers", href: "/careers/learning-and-growth", kind: "Learning" },
          { date: "2026-08-21", title: "Six things I wish I had known before my first client week", href: "/careers/early-careers", kind: "Early careers" },
          { date: "2026-08-07", title: "What our interviewers actually write down", href: "/careers/interview-tips", kind: "Hiring" },
          { date: "2026-07-24", title: "Inside a Wednesday design critique in the Lisbon studio", href: "/careers/working-here", kind: "Design" },
          { date: "2026-07-10", title: "Twenty weeks of parental leave, from both sides of the handover", href: "/careers/benefits", kind: "Benefits" },
        ],
      },
      {
        type: "cta",
        heading: "Write the next story with us",
        text: "Every open role, in every studio.",
        cta: { label: "Search for jobs", href: "/careers/search-for-jobs" },
        secondary: { label: "Careers home", href: "/careers" },
        image: "misty-valley",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/careers/hiring-journey",
    title: "Hiring Journey",
    section: "How we hire",
    summary: "Each step, from application to offer.",
    blocks: [
      {
        type: "hero",
        variant: "split",
        eyebrow: "How we hire",
        title: "From application to offer, step by step",
        lead: "Four conversations at most, a reply at every step, and usually an answer within four weeks. Here is exactly what to expect.",
        cta: { label: "See open roles", href: "/careers/search-for-jobs" },
        image: "bridge-cables",
      },
      {
        type: "intro",
        text: "Hiring is the most important decision we make, and it should feel like a fair conversation in both directions. You will meet the people you would work with, see a realistic piece of the work, and get honest feedback whatever the outcome.",
        body: [
          "The steps are the same in every studio and every area. Graduate and internship applications follow the same path, with a group session in place of the working session.",
        ],
      },
      {
        type: "steps",
        eyebrow: "The steps",
        heading: "What happens, and when",
        items: [
          { title: "Apply", text: "Send your CV or a short profile, and a few lines on why this role. No cover letter templates. It takes about fifteen minutes." },
          { title: "We read it", text: "A person on the hiring team reads every application and replies within ten working days, yes or no." },
          { title: "First conversation", text: "Thirty minutes on video with someone from the team: the work, the client, what you want next. Bring questions." },
          { title: "Working session", text: "Ninety minutes with two future colleagues on a realistic problem. You can use your own tools and look things up." },
          { title: "Meet the partners", text: "Forty-five minutes on how we work, what we value and what you would change. It goes both ways." },
          { title: "Offer or feedback", text: "Within five working days, an offer with your level and pay band, or written feedback you can use." },
        ],
      },
      {
        type: "stats",
        tone: "paper",
        heading: "How long it takes",
        items: [
          { value: "10 days", label: "at most from application to a reply, in working days." },
          { value: "4 weeks", label: "from application to offer, at the median, in 2025." },
          { value: "4", label: "conversations at most, including the first one." },
          { value: "100%", label: "of candidates who reach the working session receive written feedback." },
        ],
        source: "KIASA hiring records, 2025. Sample figures.",
      },
      {
        type: "accordion",
        heading: "Questions about each step",
        items: [
          { title: "Is there a take-home test?", body: ["No. We do not ask for unpaid work. The working session happens together, at a time we agree, and it ends when the session ends."] },
          { title: "Who will I meet?", body: ["People from the team you would join, at the first conversation and the working session, then two partners. You will have names and roles before each meeting."] },
          { title: "Can I do the interviews in person?", body: ["Yes, at any of our studios. Most people choose video for the first conversation and come in for the working session, but it is your choice."] },
          { title: "How do you decide?", body: ["Each interviewer writes notes against the same published criteria before talking to anyone else. The panel then meets once to decide. Nobody's view counts double."], link: { label: "What we look for", href: "/careers/interview-tips" } },
          { title: "What if I need adjustments?", body: ["Tell us at any point, for any reason. Extra time, written questions in advance, a different format: we arrange it, and it plays no part in our decision."] },
        ],
      },
      {
        type: "split",
        eyebrow: "After you say yes",
        heading: "Your first weeks, planned before you arrive",
        body: [
          "Once you accept, you get a named buddy from your studio and a plan for your first four weeks. Your equipment arrives before your first day, and you meet your project team in the first week.",
          "Ownership begins after your first year. Everything else starts on day one.",
        ],
        cta: { label: "Read about benefits", href: "/careers/benefits" },
        image: "desktop-tablet",
        side: "left",
      },
      {
        type: "quote",
        text: "I did not get the first role I applied for. The feedback was specific enough that I knew what to work on, and eight months later I applied again and got the job. I still have that email.",
        name: "Leila Ahmadi",
        role: "Data Scientist, Toronto",
        image: "arch-bridge",
      },
      {
        type: "cta",
        heading: "Start with one application",
        text: "Find the role that fits, and read how to prepare.",
        cta: { label: "Search for jobs", href: "/careers/search-for-jobs" },
        secondary: { label: "Interview tips", href: "/careers/interview-tips" },
        image: "bridge-fog",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/careers/interview-tips",
    title: "Interview Tips",
    section: "How we hire",
    summary: "What we look for, and how to prepare.",
    blocks: [
      {
        type: "hero",
        variant: "split",
        eyebrow: "How we hire",
        title: "What we look for, and how to prepare",
        lead: "Our interviews are built to show how you work, not how well you perform under pressure. A little preparation goes a long way.",
        cta: { label: "See each step of hiring", href: "/careers/hiring-journey" },
        image: "desk-above",
      },
      {
        type: "intro",
        text: "We publish the criteria every interviewer uses. There are no hidden questions and no trick puzzles. If you know what we are looking for, you can show it, and if you do not have it yet, we would rather you knew that too.",
      },
      {
        type: "features",
        eyebrow: "The criteria",
        heading: "What every interviewer looks for",
        numbered: true,
        items: [
          { title: "Care for the craft", text: "You can explain why you made a choice, and what you would do differently with more time." },
          { title: "Clear thinking out loud", text: "You talk us through a problem as you solve it. We are interested in the route, not just the answer." },
          { title: "Curiosity about people", text: "You ask who will use the thing and who will run it, before you decide how to build it." },
          { title: "Honesty about limits", text: "You say when you do not know. It is one of the strongest signals we see." },
          { title: "Working well with others", text: "You build on a colleague's idea and disagree without making it personal." },
          { title: "Thinking about handover", text: "You consider how someone else will understand, change and run what you made." },
        ],
      },
      {
        type: "accordion",
        heading: "How to prepare for each conversation",
        items: [
          { title: "Your application", body: ["Keep it short. Tell us about two or three pieces of work you are proud of and what your part was. Links to code, designs or writing help more than a long list of tools."] },
          { title: "The first conversation", body: ["Read a little about the work we do in your area, and come with questions. We will ask what you want from your next role; a clear answer helps us both."], link: { label: "Career areas", href: "/careers/career-areas" } },
          { title: "The working session", body: ["You will get the brief a few days ahead. You do not need to prepare a solution. Do make sure your tools work, and practice explaining your thinking as you go.", "For design and data roles, the session is a short critique and a problem to frame together, rather than code."] },
          { title: "Meeting the partners", body: ["This is about values and ways of working. Think of a time you disagreed with a decision, and a time you changed your mind. Ask the partners anything about how KIASA is run."] },
          { title: "If you need adjustments", body: ["Ask at any stage. We can share questions in advance, allow extra time or change the format. It will not affect our decision."] },
        ],
      },
      {
        type: "split",
        eyebrow: "On the day",
        heading: "Small things that help",
        body: [
          "Use the tools you know. Look things up when you would at work; we do too. Take a minute to think before answering, and ask us to repeat or rephrase anything.",
          "Leave time at the end for your own questions. The best ones are about how the work really happens: how a team decides, what went wrong on a recent project, what a partner's week looks like.",
        ],
        image: "tablet-hand",
        side: "right",
      },
      {
        type: "quote",
        text: "The candidates who stand out are rarely the ones with the fastest answer. They are the ones who ask who will be running this in two years, and change their design when they hear the answer.",
        name: "Marta Lopes",
        role: "Principal Engineer, Lisbon",
        image: "vaulted-ceiling",
      },
      {
        type: "cards",
        eyebrow: "Before you interview",
        heading: "Read what we think",
        intro: "A good way to see how we work is to read what we write.",
        items: [
          { kind: "Perspective", title: "Why the second year of a cloud migration matters more than the first", summary: "Costs, habits and ownership settle in year two, and that is where most of the promised value is won or lost.", href: "/insights/second-year-of-a-cloud-migration", art: "strata", surface: "paper" },
          { kind: "Research report", title: "The maintenance dividend", summary: "We asked 140 engineering leaders where their budgets go. On average, 61% is spent keeping existing systems running.", href: "/insights/the-maintenance-dividend", art: "glass-roof" },
          { kind: "Perspective", title: "Green software is mostly just good software", summary: "The code that wastes the least energy is usually the code that is simplest to run.", href: "/insights/green-software-is-good-software", art: "rings", surface: "night" },
          { kind: "Case study", title: "How Halden Mutual settles claims in two days, not nine", summary: "A 90-year-old insurer replaced its claims core without a freeze, one product line at a time.", href: "/client-stories/halden-mutual", art: "power-lines" },
        ],
      },
      {
        type: "cta",
        heading: "Prepared? Find your role",
        text: "Every open role, in every studio.",
        cta: { label: "Search for jobs", href: "/careers/search-for-jobs" },
        secondary: { label: "Hiring journey", href: "/careers/hiring-journey" },
        image: "above-clouds",
      },
    ],
  },
];
