import type { MediaBlock, PageDoc } from "../blocks";

/**
 * Client stories: the listing, the film series "Grown with KIASA" and the four case studies.
 * SAMPLE CONTENT: the clients, people and figures are invented for the design review.
 */

type Story = MediaBlock["items"][number];

/** Each story keeps one photograph across the site, so a reader recognizes it. */
const story = {
  halden: {
    image: "forest-path",
    eyebrow: "Insurance",
    title: "How Halden Mutual settles claims in two days, not nine",
    text: "A 90-year-old insurer replaced its claims core one product line at a time, without a freeze.",
    href: "/client-stories/halden-mutual",
    cta: "Read the case study",
  },
  osprey: {
    image: "light-trails",
    eyebrow: "Logistics and Transport",
    title: "Osprey Freight plans 4,000 routes a night on one platform",
    text: "Three regional planning tools became one, and the plan is ready 50 minutes after the order cutoff.",
    href: "/client-stories/osprey-freight",
    cta: "Read the case study",
  },
  tessera: {
    image: "bright-room",
    eyebrow: "Healthcare",
    title: "Tessera Health brings 38 clinics onto a single patient record",
    text: "Five record systems became one, moved clinic by clinic over weekends, without losing a document.",
    href: "/client-stories/tessera-health",
    cta: "Read the case study",
  },
  varda: {
    image: "wind-road",
    eyebrow: "Energy and Utilities",
    title: "Varda Energy reads two million meters without a mainframe",
    text: "96 million readings a day, and a mainframe switched off without a single billing error.",
    href: "/client-stories/varda-energy",
    cta: "Read the case study",
  },
  film: {
    image: "misty-valley",
    eyebrow: "Film series",
    title: "Grown with KIASA",
    text: "The people who run these systems tell the story in their own words. Six short films.",
    href: "/client-stories/grown-with-kiasa",
    cta: "Watch the series",
  },
} satisfies Record<string, Story>;

const talk = { label: "Talk to us", href: "/contact" };

export const clientStoriesPages: PageDoc[] = [
  /* ------------------------------------------------------------------ */
  {
    href: "/client-stories",
    title: "Client stories",
    section: "KIASA",
    summary: "How the systems we helped build are working today, told by the people who run them.",
    blocks: [
      {
        type: "hero",
        variant: "photo",
        eyebrow: "Client stories",
        title: "Still working, years later",
        lead: "How the systems we helped build are working today, told by the people who run them.",
        body: [
          "We judge our work by what happens after we leave. These are the clients who let us go back and ask.",
        ],
        image: "forest-canopy",
      },
      {
        type: "intro",
        eyebrow: "Why we tell them this way",
        text: "A launch is easy to celebrate. What matters is whether the system is still doing its job two years later, run by the client's own people, and whether they would choose it again. Each story here was checked with the client, figures included.",
        body: [
          "Every case study names the problem as the client saw it, what we did together, and the result in numbers the client measured, not us.",
          "Some of the people who run these systems also tell the story on film, in Grown with KIASA.",
        ],
      },
      {
        type: "media",
        eyebrow: "Case studies",
        heading: "Featured client stories",
        intro: "Four core systems replaced or rebuilt without stopping the business that depended on them.",
        items: [story.halden, story.osprey, story.tessera, story.varda],
      },
      {
        type: "film",
        eyebrow: "Film series",
        heading: "Grown with KIASA",
        text: "Six short films from the field, hosted by our managing partner, Elena Marsh. The people who run the systems we helped build describe what changed, what was hard and what they would do differently.",
        image: "mountain-lake",
        duration: "1:45",
      },
      {
        type: "stats",
        tone: "paper",
        eyebrow: "After we leave",
        heading: "What our clients kept",
        items: [
          { value: "9 in 10", label: "Clients we worked with in 2023 who still work with us today." },
          { value: "94%", label: "Clients who say they would recommend KIASA to a peer." },
          { value: "87%", label: "Systems we have built since 2020 that are now run by the client's own team." },
        ],
        source: "KIASA client survey, June 2026, and engagement records since 2020.",
      },
      {
        type: "quote",
        text: "KIASA built it with us, then made sure we did not need them to run it. Two years on, our own team ships changes every week.",
        name: "Sofia Lindgren",
        role: "Chief Information Officer, Varda Energy",
        image: "rocky-coast",
      },
      {
        type: "media",
        eyebrow: "More from the field",
        heading: "Smaller stories, same habits",
        intro: "Not every engagement is a core replacement. A few of the shorter pieces of work we are proud of.",
        items: [
          {
            image: "college-lawn",
            eyebrow: "Education",
            title: "Aldermoor University enrolls students in 20 minutes, online",
            text: "A student records system rebuilt over two summers. Enrollment day no longer means a queue around the building.",
            href: "/what-we-do/industries/education",
            cta: "See Education",
          },
          {
            image: "rail-tracks",
            eyebrow: "Logistics and Transport",
            title: "Brannock Rail publishes timetable changes in five minutes",
            text: "A planning tool that sends every change to every station display and online trip planner within five minutes.",
            href: "/what-we-do/industries/logistics-and-transport",
            cta: "See Logistics and Transport",
          },
          {
            image: "towers-up",
            eyebrow: "Banking and Payments",
            title: "Fernhill Building Society reads 4,000 invoices a week with AI",
            text: "A model reads the invoices; the finance team checks the forty it is unsure of.",
            href: "/what-we-do/industries/banking-and-payments",
            cta: "See Banking and Payments",
          },
          {
            image: "industrial-plant",
            eyebrow: "Manufacturing",
            title: "Calder Works cuts compute hours by 38% without touching its code",
            text: "Test environments switched off at night, and a carbon figure on every order.",
            href: "/what-we-do/industries/manufacturing",
            cta: "See Manufacturing",
          },
        ],
      },
      {
        type: "links",
        heading: "Browse client stories",
        groups: [
          {
            label: "Case studies and film",
            links: [
              { title: "Halden Mutual", href: "/client-stories/halden-mutual", summary: "Claims settled in two days, not nine." },
              { title: "Osprey Freight", href: "/client-stories/osprey-freight", summary: "4,000 routes a night on one platform." },
              { title: "Tessera Health", href: "/client-stories/tessera-health", summary: "38 clinics on a single patient record." },
              { title: "Varda Energy", href: "/client-stories/varda-energy", summary: "Two million meters read without a mainframe." },
              { title: "Grown with KIASA", href: "/client-stories/grown-with-kiasa", summary: "The film series, hosted by our managing partner." },
            ],
          },
          {
            label: "By industry",
            links: [
              { title: "Insurance", href: "/what-we-do/industries/insurance" },
              { title: "Logistics and Transport", href: "/what-we-do/industries/logistics-and-transport" },
              { title: "Healthcare", href: "/what-we-do/industries/healthcare" },
              { title: "Energy and Utilities", href: "/what-we-do/industries/energy-and-utilities" },
            ],
          },
          {
            label: "By capability",
            links: [
              { title: "Application Modernization", href: "/what-we-do/capabilities/application-modernization" },
              { title: "Integration and APIs", href: "/what-we-do/capabilities/integration-and-apis" },
              { title: "Cloud and Platform Engineering", href: "/what-we-do/capabilities/cloud-and-platform-engineering" },
              { title: "Managed Services", href: "/what-we-do/capabilities/managed-services" },
            ],
          },
        ],
      },
      {
        type: "cta",
        heading: "Have a system that has to keep working?",
        text: "Tell us what you are replacing or building, and what cannot stop while you do. A partner will reply within two working days.",
        cta: talk,
        secondary: { label: "Read what we think", href: "/insights" },
        image: "leaf-drops",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/client-stories/grown-with-kiasa",
    title: "Grown with KIASA",
    section: "Film series",
    summary: "The people who run the systems we helped build tell the story in their own words. A short film series from the field, hosted by our managing partner.",
    blocks: [
      {
        type: "hero",
        variant: "photo",
        eyebrow: "Film series",
        title: "Grown with KIASA",
        lead: "The people who run the systems we helped build tell the story in their own words. A short film series from the field, hosted by our managing partner.",
        body: [
          "Six films, each about four minutes long, recorded where the work happens: claims floors, depots, clinics and control rooms.",
          "No scripts and no actors. We asked what changed, what was hard, and what they would do differently.",
        ],
        image: "misty-valley",
      },
      {
        type: "film",
        eyebrow: "Now showing",
        heading: "Episode 3: Varda Energy, the quiet migration",
        text: "Two million smart meters moved off a mainframe in groups of 50,000, and not one customer called to ask why. Kenji Arakawa and his team explain how they kept it quiet.",
        image: "hiker-valley",
        duration: "4:12",
        episodes: [
          { title: "Episode 1. Halden Mutual: one product line at a time", duration: "4:38", image: "city-overlook", text: "Ingrid Solberg on replacing a claims core while the business kept selling." },
          { title: "Episode 2. Osprey Freight: the plan by eight", duration: "3:52", image: "harbour-crane", text: "Meera Pillai and the planners who used to work until midnight." },
          { title: "Episode 3. Varda Energy: the quiet migration", duration: "4:12", image: "lake-figure", text: "Kenji Arakawa on moving two million meters without anyone noticing." },
          { title: "Episode 4. Tessera Health: one record, 38 clinics", duration: "4:26", image: "cafe-windows", text: "Dr. Amara Nwosu on moving clinics at weekends so Monday was a normal day." },
          { title: "Episode 5. Aldermoor University: enrollment without the queue", duration: "3:34", image: "college-lawn", text: "Fiona Gallagher on two summers of rebuilding a student records system." },
          { title: "Episode 6. Brannock Rail: timetables that change on time", duration: "3:48", image: "train-carriage", text: "Youssef Haddad on getting a timetable change to every station in five minutes." },
        ],
      },
      {
        type: "intro",
        eyebrow: "About the series",
        heading: "Told by the people who run them",
        text: "Case studies tell you what a system does. These films tell you what it is like to own one: the night before go-live, the first storm on a new claims platform, the day a clinic forgot which system it used to have.",
        body: [
          "Elena Marsh, our managing partner, visits each client and asks the same three questions: what changed, what was hard, and what would you do differently. The answers are not always flattering to us, and we have kept them in.",
          "Each episode links to the full case study, with the numbers behind the story.",
        ],
      },
      {
        type: "people",
        tone: "paper",
        eyebrow: "In the films",
        heading: "Who you will hear from",
        items: [
          { name: "Elena Marsh", role: "Managing Partner, KIASA", bio: "Host of the series." },
          { name: "Ingrid Solberg", role: "Chief Claims Officer, Halden Mutual", bio: "Led the claims side of Halden's core replacement." },
          { name: "Meera Pillai", role: "Vice President, Network Planning, Osprey Freight", bio: "Runs the team that plans 4,000 routes a night." },
          { name: "Kenji Arakawa", role: "Head of Metering Systems, Varda Energy", bio: "Leads the platform team that took over from the mainframe." },
          { name: "Dr. Amara Nwosu", role: "Chief Medical Information Officer, Tessera Health", bio: "Signed off every clinical data mapping in the move to one record." },
          { name: "Fiona Gallagher", role: "Registrar, Aldermoor University", bio: "Owns enrollment for 18,000 students." },
          { name: "Youssef Haddad", role: "Head of Timetabling, Brannock Rail", bio: "Plans the timetable for 140 stations." },
        ],
      },
      {
        type: "quote",
        text: "We did not want a showreel. We wanted the people who live with these systems to say, in their own words, whether they were worth it. Most of them said yes. One of them told us what we got wrong, and that is in the film too.",
        name: "Elena Marsh",
        role: "Managing Partner, KIASA",
        image: "camera-hands",
      },
      {
        type: "split",
        eyebrow: "How the films are made",
        heading: "A small crew, a day on site, no script",
        body: [
          "A crew of three spends a day with each client. We film the work as it happens and interview the people who do it. The client sees the cut before anyone else and can remove anything that is commercially sensitive. They cannot add claims that their own numbers do not support.",
          "Every figure in a film is checked against the client's own records and appears in the matching case study.",
        ],
        image: "cafe-table",
        side: "left",
      },
      {
        type: "media",
        eyebrow: "The full stories",
        heading: "Read the case studies behind the films",
        items: [story.halden, story.osprey, story.tessera, story.varda],
      },
      {
        type: "cta",
        heading: "Tell us about a system you want to last",
        text: "If you are about to replace something your business cannot do without, we would like to hear about it.",
        cta: talk,
        secondary: { label: "All client stories", href: "/client-stories" },
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/client-stories/halden-mutual",
    title: "How Halden Mutual settles claims in two days, not nine",
    section: "Case study",
    summary: "A 90-year-old insurer replaced its claims core without a freeze, one product line at a time. Its customers noticed only that things got faster.",
    blocks: [
      {
        type: "hero",
        variant: "article",
        eyebrow: "Case study",
        title: "How Halden Mutual settles claims in two days, not nine",
        lead: "A 90-year-old insurer replaced its claims core without a freeze, one product line at a time. Its customers noticed only that things got faster.",
        image: "forest-path",
        meta: ["April 14, 2026", "6 minute read", "Insurance"],
      },
      {
        type: "facts",
        items: [
          { label: "Client", value: "Halden Mutual" },
          { label: "Industry", value: "Insurance" },
          { label: "Region", value: "Northern Europe" },
          { label: "Policies", value: "1.2 million" },
          { label: "Duration", value: "2023 to 2026" },
          { label: "Team", value: "14 at peak, KIASA and Halden" },
        ],
      },
      {
        type: "intro",
        eyebrow: "The challenge",
        heading: "A claims core that could not be paused",
        text: "Halden Mutual has insured homes, cars, travelers and small businesses since 1936. Its claims system was written in 1994 and ran overnight in batches. A simple claim took nine days to settle, and every past attempt to change the system had needed a freeze the business could no longer afford.",
        body: [
          "Newer insurers were paying simple claims in a day. Halden's customers were loyal, but its complaint figures were rising and its brokers had started to say so.",
          "The board set one condition for any replacement: Halden would keep selling, keep paying claims and keep launching products throughout.",
        ],
      },
      {
        type: "prose",
        aside: {
          heading: "At a glance",
          points: [
            "Claims core replaced one product line at a time, from 2023 to 2025.",
            "Old and new systems ran in parallel for six weeks after every move.",
            "No product freeze and no planned downtime in three years.",
            "A straightforward claim now settles in two days on average, down from nine.",
          ],
        },
        items: [
          { h: "The challenge" },
          { p: "Halden's claims system was built for a business that settled claims by post. A claim reported on Monday was registered overnight, checked the next night and paid, at best, the following week. By 2022 a straightforward claim took nine days on average to settle. Handlers kept their own spreadsheets to track what the system could not, and the four people who understood its code were all within ten years of retirement." },
          { p: "Replacing it was the obvious answer and the frightening one. The system held 1.2 million policies across four product lines. The last attempt to change it, in 2017, had frozen new products for eight months and was stopped halfway." },
          { h: "The approach" },
          { p: "We proposed moving one product line at a time, starting with the smallest. Travel went first: 80,000 policies, simple claims and a season that ends in September. A new claims platform took over travel claims while the old system carried on with everything else. A routing layer in front of both sent each claim to the right place, so customers and brokers saw no change of address, phone number or form." },
          { p: "For six weeks after each move, both systems processed the same claims, and an overnight report compared every payment. Any difference was investigated before the old system's share of that line was switched off. Across the whole program, 23 differences were found. All 23 turned out to be errors in the old system." },
          { quote: "We kept selling, kept paying claims and kept launching products the whole time. That was the condition, and it held.", by: "Rafael Duarte, Chief Information Officer, Halden Mutual" },
          { p: "Claims handlers were part of the team from the first week. Eight of them spent two days a week with our designers and engineers, deciding how the new screens should work and which old workarounds could go. They then trained their colleagues, one product line at a time." },
          { figure: "design-table", caption: "Claims handlers designed the new screens with us, two days a week, from the first week." },
          { h: "What the new platform does" },
          {
            list: [
              "Registers a claim the moment it is reported, online, by phone or through a broker.",
              "Checks cover and runs fraud rules in seconds, not overnight.",
              "Pays approved claims straight away, with no batch to wait for.",
              "Gives handlers one screen for the claim, the policy and every message about it.",
            ],
          },
          { h: "The outcome" },
          { p: "The last product line, small business, moved in December 2025. The old system was switched off in March 2026, and its records archived where auditors can still reach them. Halden's own platform team, built up alongside ours, now runs and extends the platform. In September 2026 the two firms extended their partnership through 2030." },
          { stat: "2 days", label: "Average time to settle a straightforward claim, down from nine." },
          { p: "41% of travel claims are now paid within 24 hours of being reported. Handlers spend about a third less time on each claim, and that time has gone into the complex claims where a person makes the most difference." },
        ],
      },
      {
        type: "stats",
        eyebrow: "Results",
        heading: "What changed for Halden's customers",
        items: [
          { value: "2 days", label: "Average time to settle a straightforward claim, down from nine." },
          { value: "0", label: "Weeks of product freeze during the three-year replacement." },
          { value: "35%", label: "Less handler time spent on each claim." },
          { value: "27%", label: "Fewer complaints about claims in 2025 than in 2022." },
        ],
        source: "Halden Mutual claims and complaints data, 2022 to 2026.",
      },
      {
        type: "quote",
        text: "Our customers did not notice the replacement. They noticed that their money arrived on Wednesday instead of the week after next. That is exactly how we wanted it.",
        name: "Ingrid Solberg",
        role: "Chief Claims Officer, Halden Mutual",
        image: "arch-bridge",
      },
      {
        type: "steps",
        tone: "paper",
        eyebrow: "How the work ran",
        heading: "One product line at a time",
        items: [
          { title: "Travel, 2023", text: "The smallest line went first. 80,000 policies moved before the summer season, and the routing layer proved itself." },
          { title: "Motor, 2024", text: "The busiest line, with the most partners. Garages, hire firms and assessors were connected through new APIs." },
          { title: "Home, 2024 to 2025", text: "The most complex claims. The first big storm on the new platform came in November 2024, and it held." },
          { title: "Small business, 2025", text: "The last line moved in December 2025. The old system was switched off in March 2026." },
          { title: "Handover", text: "Halden's own platform team runs and extends the system, with KIASA alongside through 2030." },
        ],
      },
      {
        type: "media",
        eyebrow: "More client stories",
        heading: "Other systems still working",
        items: [story.osprey, story.tessera, story.varda, story.film],
      },
      {
        type: "cta",
        heading: "Have a core system you cannot afford to pause?",
        text: "We replace core systems one part at a time, so the business keeps running throughout. Tell us what yours does and what it cannot stop doing.",
        cta: talk,
        secondary: { label: "Read about the partnership", href: "/newsroom/halden-mutual-partnership" },
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/client-stories/osprey-freight",
    title: "Osprey Freight plans 4,000 routes a night on one platform",
    section: "Case study",
    summary: "Three regional planning tools became one. The night's plan is now ready 50 minutes after the order cutoff, and planners can change it in minutes when the night changes.",
    blocks: [
      {
        type: "hero",
        variant: "article",
        eyebrow: "Case study",
        title: "Osprey Freight plans 4,000 routes a night on one platform",
        lead: "Three regional planning tools became one. The night's plan is now ready 50 minutes after the order cutoff, and planners can change it in minutes when the night changes.",
        image: "light-trails",
        meta: ["February 10, 2026", "6 minute read", "Logistics and Transport"],
      },
      {
        type: "facts",
        items: [
          { label: "Client", value: "Osprey Freight" },
          { label: "Industry", value: "Logistics and Transport" },
          { label: "Region", value: "North America" },
          { label: "Network", value: "26 depots, 1,800 vehicles" },
          { label: "Duration", value: "18 months, 2024 to 2025" },
          { label: "Team", value: "11 at peak" },
        ],
      },
      {
        type: "intro",
        eyebrow: "The challenge",
        heading: "Three tools, five hours, every night",
        text: "Every evening, between the order cutoff at 6 p.m. and the first trucks leaving at midnight, Osprey Freight plans around 4,000 routes. It used to take five hours across three planning tools, leaving no time to plan again when a truck broke down or a large order arrived late.",
        body: [
          "Osprey grew by bringing two regional carriers into the group. Each kept its own planning tool, and freight that crossed regions was handed between planners by spreadsheet.",
          "The result was trucks running empty on one side of a regional line while freight waited on the other, and planners who went home at midnight with a plan they knew was not the best one.",
        ],
      },
      {
        type: "prose",
        aside: {
          heading: "At a glance",
          points: [
            "Three regional planning tools replaced by one platform with one data model.",
            "Each region ran in shadow for six weeks before switching over.",
            "Planners keep the final say: the platform proposes, people decide.",
            "The night's plan is ready in 50 minutes instead of five hours.",
          ],
        },
        items: [
          { h: "The challenge" },
          { p: "Osprey runs an overnight parcel and pallet network from 26 depots with 1,800 vehicles. Planning starts when orders close at 6 p.m. and must be finished before loading begins. Each of the three regions planned its own routes in its own tool, with its own rules for driver hours and vehicle sizes. Cross-region freight was planned last, by hand." },
          { p: "Because the plan took five hours, it was rarely revisited. When something changed after 11 p.m., the planner on duty patched the plan by phone. Empty miles, trucks driving with nothing in them, ran at 17% of the total." },
          { h: "The approach" },
          { p: "We started by spending six weeks of nights in Osprey's planning rooms, writing down how each region actually planned, including the rules that existed only in planners' heads. From that we built one data model for orders, vehicles, drivers, depots and delivery windows, shared by all three regions." },
          { p: "On top of it sits a route optimization engine, built on an open-source solver and configured for Osprey's rules: driver hours, dock slots, vehicle sizes and customer time windows. It proposes a plan for the whole network at once, so cross-region freight is planned with everything else, not after it." },
          { quote: "We did not want a black box. The planners can see why the platform chose each route, and they can overrule it. That is why they use it.", by: "Dale Hutchins, Chief Technology Officer, Osprey Freight" },
          { p: "Each region then ran in shadow for six weeks. The new platform planned the same night as the old tool, and planners compared the two each morning. Only when the planners themselves preferred the new plan for two weeks running did the region switch over. The eastern region went first, in March 2025; the last switched in October." },
          { figure: "interchange", caption: "One plan for the whole network: cross-region freight is planned with everything else, not last." },
          { h: "What changed for the planners" },
          {
            list: [
              "The first complete plan is ready 50 minutes after the order cutoff.",
              "Depot scanners and vehicle telematics feed the plan, so it updates as the night goes on.",
              "When a truck breaks down, the platform proposes a new plan for the affected routes in minutes.",
              "Every route shows why it was chosen, and planners can lock or change any part of it.",
            ],
          },
          { h: "The outcome" },
          { p: "Since October 2025, all 4,000 nightly routes have been planned on one platform. Empty miles have fallen by 11%, fuel use by 8%, and on-time delivery has risen from 91% to 97%. Planners now finish their shift with a plan they trust, and spend the time they got back on the exceptions that need a person." },
          { stat: "50 min", label: "From order cutoff to a complete plan for the whole network, down from five hours." },
          { p: "Osprey's own platform team, trained alongside ours from the first month, now runs the platform and has since added a fourth planning rule set for a new refrigerated service." },
        ],
      },
      {
        type: "stats",
        eyebrow: "Results",
        heading: "A better plan, sooner",
        items: [
          { value: "4,000", label: "Routes planned every night, on one platform." },
          { value: "50 min", label: "From the order cutoff to a complete plan, down from five hours." },
          { value: "11%", label: "Fewer empty miles across the network." },
          { value: "97%", label: "On-time deliveries, up from 91% before the change." },
        ],
        source: "Osprey Freight operations data, 2024 to 2026.",
      },
      {
        type: "quote",
        text: "My planners used to go home at midnight with a plan they knew was wrong. Now they go home at eight with one they trust, and when a truck breaks down, the platform fixes the plan before the phone stops ringing.",
        name: "Meera Pillai",
        role: "Vice President, Network Planning, Osprey Freight",
        image: "night-traffic",
      },
      {
        type: "steps",
        tone: "paper",
        eyebrow: "How the work ran",
        heading: "Eighteen months, region by region",
        items: [
          { title: "Map the night", text: "Six weeks in the planning rooms, writing down every rule, including the unwritten ones." },
          { title: "One data model", text: "Orders, vehicles, drivers, depots and delivery windows, described once for all three regions." },
          { title: "Shadow planning", text: "Six weeks per region with both tools planning the same night, compared every morning." },
          { title: "Region by region", text: "The east switched in March 2025, the central region in July and the west in October." },
          { title: "Handover", text: "Osprey's platform team runs and extends the platform, with KIASA on call." },
        ],
      },
      {
        type: "media",
        eyebrow: "More client stories",
        heading: "Other systems still working",
        items: [story.halden, story.tessera, story.varda, story.film],
      },
      {
        type: "cta",
        heading: "Planning something that has to be right by morning?",
        text: "We build planning and optimization platforms that people trust because they can see how they work. Tell us about your night.",
        cta: talk,
        secondary: { label: "See Logistics and Transport", href: "/what-we-do/industries/logistics-and-transport" },
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/client-stories/tessera-health",
    title: "Tessera Health brings 38 clinics onto a single patient record",
    section: "Case study",
    summary: "Five record systems became one. Tessera Health moved 38 clinics, 420,000 patients and 2.1 million documents onto a single patient record, wave by wave over weekends.",
    blocks: [
      {
        type: "hero",
        variant: "article",
        eyebrow: "Case study",
        title: "Tessera Health brings 38 clinics onto a single patient record",
        lead: "Five record systems became one. Tessera Health moved 38 clinics, 420,000 patients and 2.1 million documents onto a single patient record, wave by wave over weekends.",
        image: "bright-room",
        meta: ["August 4, 2026", "7 minute read", "Healthcare"],
      },
      {
        type: "facts",
        items: [
          { label: "Client", value: "Tessera Health" },
          { label: "Industry", value: "Healthcare" },
          { label: "Region", value: "Asia Pacific" },
          { label: "Clinics", value: "38" },
          { label: "Patients", value: "420,000" },
          { label: "Duration", value: "2024 to 2026" },
        ],
      },
      {
        type: "intro",
        eyebrow: "The challenge",
        heading: "Five record systems, one patient",
        text: "Tessera Health grew from 9 clinics to 38 in eight years, mostly by welcoming existing practices into the group. Each brought its own patient record system. By 2023 there were five, and a patient who visited two Tessera clinics had two records that knew nothing about each other.",
        body: [
          "Clinicians looked up history in several systems, or asked the patient. Referrals between clinics went by PDF. The same blood test was sometimes ordered twice in a week.",
          "Tessera wanted one record for every patient, in every clinic, without a single day on which a clinic could not see its patients' notes.",
        ],
      },
      {
        type: "prose",
        aside: {
          heading: "At a glance",
          points: [
            "One record platform, configured rather than customized, for all 38 clinics.",
            "512,000 records from five systems matched into 420,000 patients.",
            "Clinics moved in eight waves, always over a weekend.",
            "Not one of 2.1 million documents was lost.",
          ],
        },
        items: [
          { h: "The challenge" },
          { p: "Every system Tessera had inherited worked, more or less, for the clinic that chose it. None worked for the group. A patient's allergies might be recorded in one system and not another. A specialist clinic receiving a referral re-typed the patient's details from a PDF. Reports for regulators were assembled by hand from five exports each quarter." },
          { p: "Clinical staff were wary. Several had been through a failed system change elsewhere, and they knew that a bad Monday morning in a clinic means patients turned away." },
          { h: "The approach" },
          { p: "Tessera chose one established record platform, and we agreed early to configure it rather than customize it. Across the whole program we made fewer than 20 changes to the product itself. That keeps upgrades simple, and it means Tessera's team can run the platform without us." },
          { p: "The hardest part was the patients themselves. Five systems held 512,000 records, many describing the same person with a different spelling, an old address or a missing date of birth. Automated matching combined them into 420,000 patients. The 6,300 uncertain matches were reviewed one by one by clinical staff, never by the algorithm alone." },
          { quote: "We moved clinics at weekends so that Monday was a normal day. Our super users knew the new system better than we did by the time it arrived.", by: "Hannah Lowe, Director of Clinic Operations, Tessera Health" },
          { p: "Clinics moved in eight waves of four to six, always from Friday evening to Sunday. Two super users in each clinic were trained four weeks ahead, and our engineers were on site at every clinic on the Monday morning after its move. Tessera's clinical safety lead signed off every data mapping before it ran." },
          { figure: "tablet-hand", caption: "One record, in every room of every clinic, from the first Monday." },
          { h: "What changed in the clinics" },
          {
            list: [
              "Every clinician sees a patient's full history from every Tessera clinic in one place.",
              "Allergies, medicines and alerts are recorded once and shown everywhere.",
              "Referrals arrive as part of the record, the same day, with nothing to re-type.",
              "Regulatory reports run from one system in minutes, not from five exports over days.",
            ],
          },
          { h: "The outcome" },
          { p: "The last wave moved in June 2026. Today every one of Tessera's 38 clinics works from a single patient record. Finding a patient's full history takes under 30 seconds, where it used to take six minutes and several logins. Duplicate tests have fallen by 22%, and referrals arrive the same day instead of after five." },
          { stat: "0", label: "Documents lost out of 2.1 million migrated, checked by count and checksum for every clinic." },
          { p: "Tessera's own team now runs the platform and the training program for new staff. The next clinic to join the group will move onto the shared record in a single weekend, using the same playbook." },
        ],
      },
      {
        type: "stats",
        eyebrow: "Results",
        heading: "One record, every clinic",
        items: [
          { value: "38", label: "Clinics working from a single patient record." },
          { value: "30 sec", label: "To find a patient's full history, down from six minutes." },
          { value: "22%", label: "Fewer duplicate tests ordered across the group." },
          { value: "0", label: "Documents lost out of 2.1 million migrated." },
        ],
        source: "Tessera Health clinical operations data, 2023 to 2026.",
      },
      {
        type: "quote",
        text: "The best thing anyone said to me after the last wave was a nurse who had forgotten which system her clinic used to have. In healthcare technology, that is what success sounds like.",
        name: "Dr. Amara Nwosu",
        role: "Chief Medical Information Officer, Tessera Health",
        image: "vaulted-ceiling",
      },
      {
        type: "steps",
        tone: "paper",
        eyebrow: "How the work ran",
        heading: "Eight waves over two years",
        items: [
          { title: "Choose and configure", text: "One record platform, configured for Tessera's clinics with fewer than 20 product changes." },
          { title: "Match the patients", text: "512,000 records matched into 420,000 patients, with every uncertain match reviewed by clinical staff." },
          { title: "Train the super users", text: "Two per clinic, trained four weeks before their clinic moved." },
          { title: "Move in waves", text: "Eight waves of four to six clinics, each over a weekend, from late 2024 to June 2026." },
          { title: "Hand over", text: "Tessera's team runs the platform and the playbook for clinics that join in future." },
        ],
      },
      {
        type: "media",
        eyebrow: "More client stories",
        heading: "Other systems still working",
        items: [story.halden, story.osprey, story.varda, story.film],
      },
      {
        type: "cta",
        heading: "Bringing several systems onto one?",
        text: "We plan the move around the people who cannot stop working while it happens. Tell us how many systems you have, and how many you want.",
        cta: talk,
        secondary: { label: "See Healthcare", href: "/what-we-do/industries/healthcare" },
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/client-stories/varda-energy",
    title: "Varda Energy reads two million meters without a mainframe",
    section: "Case study",
    summary: "Varda Energy moved two million smart meters off a 1980s mainframe in groups of 50,000. Readings now reach customers in 15 minutes, and not one bill went out wrong.",
    blocks: [
      {
        type: "hero",
        variant: "article",
        eyebrow: "Case study",
        title: "Varda Energy reads two million meters without a mainframe",
        lead: "Varda Energy moved two million smart meters off a 1980s mainframe in groups of 50,000. Readings now reach customers in 15 minutes, and not one bill went out wrong.",
        image: "wind-road",
        meta: ["January 20, 2026", "6 minute read", "Energy and Utilities"],
      },
      {
        type: "facts",
        items: [
          { label: "Client", value: "Varda Energy" },
          { label: "Industry", value: "Energy and Utilities" },
          { label: "Region", value: "Europe" },
          { label: "Meters", value: "2 million" },
          { label: "Duration", value: "26 months, 2023 to 2025" },
          { label: "Team", value: "12 at peak" },
        ],
      },
      {
        type: "intro",
        eyebrow: "The challenge",
        heading: "A mainframe built for one reading a month",
        text: "Varda Energy supplies power to two million homes and businesses. Its meter data ran on a mainframe designed in the 1980s for one reading per meter per month. Smart meters send one every half hour: 96 million readings a day, arriving faster than the overnight batch could process them.",
        body: [
          "Customers saw their usage the next day at best. Late or missing readings caused billing exceptions that a team of 30 worked through by hand.",
          "Only four people still knew the mainframe's code well, and two of them planned to retire within three years. The regulator's deadline for half-hourly settlement was 2026.",
        ],
      },
      {
        type: "prose",
        aside: {
          heading: "At a glance",
          points: [
            "Meter data moved from a mainframe batch to a streaming platform in the cloud.",
            "Meters moved in 40 groups of 50,000, with six months of parallel billing.",
            "The mainframe specialists helped write down 300 rules hidden in the old code.",
            "The mainframe was switched off in November 2025, and no bill went out wrong.",
          ],
        },
        items: [
          { h: "The challenge" },
          { p: "The mainframe had served Varda well for forty years. But it was built to read each meter once a month and bill from that reading. When smart meters arrived, the volume of data grew more than a thousandfold. The overnight batch began to overrun into the morning, and on the worst days it did not finish at all." },
          { p: "Every late batch meant late readings, and every late reading risked an estimated bill. In 2022, Varda's billing team handled 41,000 exceptions by hand. Running the mainframe cost more each year, and the people who understood it were leaving." },
          { h: "The approach" },
          { p: "The first step was not code. We spent three months with Varda's four mainframe specialists, writing down what the old system actually did. They found 300 rules for validating, estimating and correcting readings, many of them added after some past incident and documented nowhere else." },
          { p: "We then built a meter data platform in the cloud that treats readings as a stream rather than a batch. Each reading is validated, corrected or estimated by the same 300 rules within minutes of arriving, and passed on to billing, settlement and the customer app." },
          { quote: "The mainframe team were not in the way of the project. They were the project. Nobody else knew what the old code really did.", by: "Sofia Lindgren, Chief Information Officer, Varda Energy" },
          { p: "Then came what Varda's team named the quiet migration. Meters moved to the new platform in 40 groups of 50,000. For six months, both systems processed every reading, and every bill was compared before it was sent. Any difference held the bill until a person had checked it. Customers were never told, because nothing about their bills was meant to change, and nothing did." },
          { figure: "power-lines", caption: "Half-hourly readings from two million meters, validated and passed on within minutes." },
          { h: "What the new platform does" },
          {
            list: [
              "Takes in 96 million readings a day as they arrive, not in a nightly batch.",
              "Applies the same 300 validation and estimation rules the mainframe used, now written down and tested.",
              "Shows customers their usage in the app within 15 minutes.",
              "Supplies half-hourly data for settlement, as the regulator now requires.",
            ],
          },
          { h: "The outcome" },
          { p: "The last group of meters moved in August 2025, and the mainframe was switched off in November. Billing exceptions have fallen by 60%, and the team that handled them by hand now works on improving the estimation rules instead. The platform costs 34% less to run than the mainframe did in its final year." },
          { stat: "96 million", label: "Meter readings processed every day, each within minutes of arriving." },
          { p: "Two of the four mainframe specialists now lead Varda's platform team. Varda runs the platform itself, ships changes every week, and has started using the same data to plan where the grid needs strengthening." },
        ],
      },
      {
        type: "stats",
        eyebrow: "Results",
        heading: "Faster data, fewer exceptions, lower cost",
        items: [
          { value: "2 million", label: "Meters read every half hour, without a mainframe." },
          { value: "15 min", label: "From a meter reading to the customer's app, instead of the next day." },
          { value: "60%", label: "Fewer billing exceptions to resolve by hand." },
          { value: "34%", label: "Lower running cost than the mainframe in its final year." },
        ],
        source: "Varda Energy metering and billing data, 2022 to 2026.",
      },
      {
        type: "quote",
        text: "We moved two million meters and not one customer called to ask why. For a migration, silence is the best review you can get.",
        name: "Kenji Arakawa",
        role: "Head of Metering Systems, Varda Energy",
        image: "bridge-fog",
      },
      {
        type: "steps",
        tone: "paper",
        eyebrow: "How the work ran",
        heading: "The quiet migration",
        items: [
          { title: "Write down the rules", text: "Three months with the mainframe specialists, documenting 300 rules for validating and estimating readings." },
          { title: "Build the stream", text: "A cloud platform that processes each reading within minutes, using the same rules, tested against old results." },
          { title: "Move 50,000 at a time", text: "40 groups of meters, moved one after another from early 2024 to August 2025." },
          { title: "Bill in parallel", text: "Six months of comparing every bill from both systems before it went out." },
          { title: "Switch off and hand over", text: "The mainframe went dark in November 2025. Varda's own team runs the platform." },
        ],
      },
      {
        type: "media",
        eyebrow: "More client stories",
        heading: "Other systems still working",
        items: [story.halden, story.osprey, story.tessera, story.film],
      },
      {
        type: "cta",
        heading: "Still running something on a mainframe?",
        text: "We move core workloads off mainframes in small, reversible steps, with the people who know the old system at the center of the work.",
        cta: talk,
        secondary: { label: "See Energy and Utilities", href: "/what-we-do/industries/energy-and-utilities" },
      },
    ],
  },
];
