import type { CardItem, PageDoc } from "../blocks";

/**
 * "What we think": the insights hub and the six pieces linked from the homepage's cards.
 * SAMPLE CONTENT: every figure, person and client below is invented for the design review.
 */

/** The pieces and the client work as cards, for the hub and the "Related" rows. */
const read = {
  canopy: {
    kind: "Announcement",
    title: "KIASA launches Canopy, a managed platform team for mid-size enterprises",
    summary: "A standing team that runs your cloud platform, keeps it secure and reports back each month in plain language.",
    href: "/canopy",
    art: "veins",
    surface: "leaf",
  },
  secondYear: {
    kind: "Perspective",
    title: "Why the second year of a cloud migration matters more than the first",
    summary: "The move itself is the easy part. Costs, habits and ownership settle in year two, and that is where most of the promised value is won or lost.",
    href: "/insights/second-year-of-a-cloud-migration",
    art: "strata",
  },
  maintenance: {
    kind: "Research report",
    title: "The maintenance dividend",
    summary: "We asked 140 engineering leaders where their budgets go. On average, 61% is spent keeping existing systems running. The best performers spend half that.",
    href: "/insights/the-maintenance-dividend",
    art: "veins",
    surface: "night",
  },
  backOffice: {
    kind: "Research report",
    title: "AI in the back office: where the first real savings are showing up",
    summary: "Across 60 finance, claims and supply teams, the returns so far come from four unglamorous tasks. We name them, with numbers.",
    href: "/insights/ai-in-the-back-office",
    art: "matrix",
  },
  pulse: {
    kind: "Research report",
    title: "Platform pulse: what engineering leaders will fund in 2027",
    summary: "Budgets are flat; expectations are not. Our annual survey of 320 technology leaders shows where the money moves next year.",
    href: "/insights/platform-pulse-2027",
    art: "pulse",
    surface: "night",
  },
  green: {
    kind: "Perspective",
    title: "Green software is mostly just good software",
    summary: "The code that wastes the least energy is usually the code that is simplest to run. A practical look at carbon as an engineering measure.",
    href: "/insights/green-software-is-good-software",
    art: "rings",
  },
  security: {
    kind: "Research report",
    title: "Security debt: the quiet risk on the balance sheet",
    summary: "Unpatched systems behave like unpaid loans: the interest compounds. A way to measure the exposure, and a plan for paying it down.",
    href: "/insights/security-debt",
    art: "contours",
    surface: "night",
  },
  halden: {
    kind: "Case study",
    title: "How Halden Mutual settles claims in two days, not nine",
    summary: "A 90-year-old insurer replaced its claims core without a freeze, one product line at a time.",
    href: "/client-stories/halden-mutual",
    art: "branches",
    surface: "leaf",
  },
  tessera: {
    kind: "Case study",
    title: "Tessera Health brings 38 clinics onto a single patient record",
    summary: "Five record systems became one, clinic by clinic, over weekends, without losing a document.",
    href: "/client-stories/tessera-health",
    art: "orbit",
    surface: "leaf",
  },
  varda: {
    kind: "Case study",
    title: "Varda Energy reads two million meters without a mainframe",
    summary: "Half-hourly reads from two million smart meters, processed in minutes on a platform Varda now runs itself.",
    href: "/client-stories/varda-energy",
    art: "waves",
    surface: "leaf",
  },
} satisfies Record<string, CardItem>;

const allInsights = { label: "All insights", href: "/insights" };
const talk = { label: "Talk to us", href: "/contact" };

export const insightsPages: PageDoc[] = [
  /* ------------------------------------------------------------------ */
  {
    href: "/insights",
    title: "What we think",
    section: "KIASA",
    summary: "Research, perspectives and field notes from our work.",
    blocks: [
      {
        type: "hero",
        variant: "plain",
        eyebrow: "What we think",
        title: "What we learn, written down",
        lead: "Research, perspectives and field notes from our work. We publish what we find in the systems we build and run, including the parts that did not go to plan.",
        pattern: "branches",
      },
      {
        type: "intro",
        eyebrow: "Our approach",
        text: "We write about what we see in our clients' systems every week: where the money goes, what breaks, what lasts. Every piece starts from data we gathered or work we did ourselves, and says plainly what we do not yet know.",
        body: [
          "Two studies run every year: The maintenance dividend, on where engineering budgets go, and Platform pulse, on what technology leaders plan to fund next. Between them we hear from more than 450 leaders a year.",
          "Perspectives are shorter. They are written by the partners and engineers who did the work, and they end with something you can do on Monday.",
        ],
      },
      {
        type: "cards",
        eyebrow: "Latest",
        heading: "Latest thinking",
        intro: "Our most recent research, perspectives and announcements. Point at a card for the short version.",
        items: [
          read.canopy,
          read.secondYear,
          read.pulse,
          { ...read.maintenance, art: "leaf-dew", surface: "photo" },
          read.backOffice,
          {
            kind: "Film series",
            title: "Grown with KIASA",
            summary: "The people who run the systems we helped build tell the story in their own words. Six short films, hosted by our managing partner.",
            href: "/client-stories/grown-with-kiasa",
            art: "misty-valley",
            surface: "photo",
          },
          read.green,
          { ...read.security, art: "leaf-drop", surface: "photo" },
        ],
      },
      {
        type: "features",
        tone: "paper",
        eyebrow: "Research programs",
        heading: "Three bodies of research, renewed every year",
        intro: "Each program asks the same core questions every year, so the answers can be compared over time.",
        items: [
          {
            title: "The maintenance dividend",
            text: "Where engineering budgets actually go, and what the teams that spend least on standing still do differently. 140 leaders in 2026.",
            pattern: "veins",
            link: { label: "Read the 2026 report", href: "/insights/the-maintenance-dividend" },
          },
          {
            title: "Platform pulse",
            text: "Our annual survey of what technology leaders will fund next year, and what they will cut to pay for it. 320 leaders this year.",
            pattern: "pulse",
            link: { label: "Read Platform pulse 2027", href: "/insights/platform-pulse-2027" },
          },
          {
            title: "Field studies",
            text: "Close studies of a single question, measured inside client teams: what AI saves in the back office, and what unpatched systems really cost.",
            pattern: "matrix",
            link: { label: "Read AI in the back office", href: "/insights/ai-in-the-back-office" },
          },
        ],
      },
      {
        type: "stats",
        eyebrow: "Behind the research",
        heading: "Where our numbers come from",
        intro: "We publish our method with every report: who we asked, when, and which answers we could check against budgets and logs.",
        items: [
          { value: "320", label: "Technology leaders surveyed for Platform pulse 2027, across ten industries." },
          { value: "140", label: "Engineering leaders who shared their budgets for The maintenance dividend." },
          { value: "60", label: "Finance, claims and supply teams measured before and after they put AI to work." },
          { value: "52", label: "Security assessments analyzed to put a number on security debt." },
        ],
        source: "KIASA research programs, 2025 to 2026. Methods are set out in each report.",
      },
      {
        type: "split",
        eyebrow: "How we write",
        heading: "Written by the people who did the work",
        body: [
          "Our authors are practitioners. The partner who led a migration writes about migrations; the engineer who cut a client's compute bill writes about carbon. Nobody writes from a brief they did not live through.",
          "We name what failed as well as what worked, we show our sample sizes, and we correct a piece in public when a later study changes the answer.",
        ],
        cta: { label: "See how we work", href: "/about/how-we-work" },
        image: "laptop-notebook",
        side: "right",
      },
      {
        type: "media",
        eyebrow: "Client stories",
        heading: "From our client work",
        intro: "The research starts here: systems we helped build, and how they are working today.",
        items: [
          { image: "forest-path", eyebrow: "Insurance", title: "How Halden Mutual settles claims in two days, not nine", text: "A claims core replaced one product line at a time, without a freeze.", href: "/client-stories/halden-mutual", cta: "Read the case study" },
          { image: "light-trails", eyebrow: "Logistics and Transport", title: "Osprey Freight plans 4,000 routes a night on one platform", text: "Three planning tools became one, and the evening shift got four hours back.", href: "/client-stories/osprey-freight", cta: "Read the case study" },
          { image: "bright-room", eyebrow: "Healthcare", title: "Tessera Health brings 38 clinics onto a single patient record", text: "One record for 420,000 patients, moved clinic by clinic over weekends.", href: "/client-stories/tessera-health", cta: "Read the case study" },
          { image: "wind-road", eyebrow: "Energy and Utilities", title: "Varda Energy reads two million meters without a mainframe", text: "96 million reads a day, and a mainframe switched off without a billing error.", href: "/client-stories/varda-energy", cta: "Read the case study" },
        ],
      },
      {
        type: "links",
        tone: "paper",
        eyebrow: "Explore",
        heading: "Explore by topic",
        groups: [
          {
            label: "Capabilities",
            links: [
              { title: "Cloud and Platform Engineering", href: "/what-we-do/capabilities/cloud-and-platform-engineering", summary: "Cloud foundations and internal platforms that make the right way the easy way." },
              { title: "Application Modernization", href: "/what-we-do/capabilities/application-modernization", summary: "Moving core systems to foundations that can change, without stopping the business." },
              { title: "Artificial Intelligence and Data", href: "/what-we-do/capabilities/artificial-intelligence-and-data", summary: "Data platforms people trust, and AI put to work on problems worth solving." },
              { title: "Cybersecurity", href: "/what-we-do/capabilities/cybersecurity", summary: "Security designed in from the first sketch, and tested the way an attacker would." },
              { title: "Green Software", href: "/what-we-do/capabilities/green-software", summary: "Measuring and cutting the energy and carbon cost of the software you run." },
            ],
          },
          {
            label: "Industries",
            links: [
              { title: "Insurance", href: "/what-we-do/industries/insurance", summary: "Policy, claims and underwriting platforms for carriers and brokers." },
              { title: "Logistics and Transport", href: "/what-we-do/industries/logistics-and-transport", summary: "Planning, tracking and settlement for freight, rail and fleets." },
              { title: "Healthcare", href: "/what-we-do/industries/healthcare", summary: "Patient records, scheduling and clinical systems that staff can rely on." },
              { title: "Energy and Utilities", href: "/what-we-do/industries/energy-and-utilities", summary: "Metering, grid data and customer platforms for the energy transition." },
            ],
          },
          {
            label: "More from KIASA",
            links: [
              { title: "Client stories", href: "/client-stories", summary: "How the systems we helped build are working today." },
              { title: "Grown with KIASA", href: "/client-stories/grown-with-kiasa", summary: "A short film series from the field." },
              { title: "Newsroom", href: "/newsroom", summary: "Announcements and news from KIASA." },
            ],
          },
        ],
      },
      {
        type: "cta",
        heading: "Get new research when it is published",
        text: "Choose the topics you care about and we will send each new report on the day it comes out. No more than two emails a month.",
        cta: { label: "Choose what you hear from us", href: "/preferences" },
        secondary: { label: "Talk to an author", href: "/contact" },
        image: "fog-forest",
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/insights/second-year-of-a-cloud-migration",
    title: "Why the second year of a cloud migration matters more than the first",
    section: "Perspective",
    summary: "The move itself is the easy part. Costs, habits and ownership settle in year two, and that is where most of the promised value is won or lost.",
    blocks: [
      {
        type: "hero",
        variant: "article",
        eyebrow: "Perspective",
        title: "Why the second year of a cloud migration matters more than the first",
        lead: "The move itself is the easy part. Costs, habits and ownership settle in year two, and that is where most of the promised value is won or lost.",
        image: "above-clouds",
        meta: ["September 24, 2026", "8 minute read", "By Mira Castell and Bruno Teixeira"],
      },
      {
        type: "prose",
        aside: {
          heading: "In brief",
          points: [
            "Across 26 migrations, cloud spend in year two ran 23% above the business case on average.",
            "One in three systems due for retirement was still running 18 months after its replacement went live.",
            "Teams carry their old release and capacity habits into the new platform unless someone changes them on purpose.",
            "The migrations that paid off had one thing in common: a funded platform team with a named owner.",
          ],
        },
        items: [
          { p: "Most cloud migrations are judged on the day the last workload moves. There is a launch note, a thank-you lunch and a slide that says 100%. Then the team that did the move rolls off, the budget line closes, and the organization settles into its new home with the habits it brought from the old one." },
          { p: "We reviewed 26 migrations we took part in between 2021 and 2026, at insurers, freight carriers, clinics, retailers and utilities. The pattern is consistent. Year one is about getting there. Year two decides whether it was worth going. In year two the bill finds its real level, the old data center either closes or lingers, and someone either owns the platform or nobody does." },
          { h: "The bill finds its level" },
          { p: "In the first year, spend often comes in below plan. Workloads arrive in waves, new environments are lightly used, and discounts for committed use have just been bought. By months 13 to 24 the picture changes. Every team has learned how easy it is to start a server. Test environments built for the migration are still running. Data that sat on tape now sits in fast storage, because nobody chose otherwise." },
          { stat: "23%", label: "Average amount by which cloud spend in months 13 to 24 exceeded the business case, across the 26 migrations we reviewed." },
          { p: "None of this is waste in the usual sense. Each decision made sense on the day it was made. The trouble is that nobody revisits them. The organizations that held to their business case did one simple thing: they put a named person in charge of the bill, gave that person a weekly report by team, and gave them the authority to switch things off." },
          { h: "Two estates cost more than one" },
          { p: "The second trap is the old estate. A migration plan usually ends with a decommissioning step, and it is the step most often left undone. A reporting server one department still uses. A license that renews by itself. A disaster recovery site kept warm just in case. Each is small. Together they mean the organization pays for two estates long after it meant to pay for one." },
          { p: "In our review, one in three systems scheduled for retirement was still running 18 months after its replacement went live. The most common reason was not technical. Nobody had been given the job of turning it off, and nobody wanted to be the person who did, in case something broke." },
          { quote: "We moved in nine months and spent the next fourteen closing the doors behind us. Nobody budgets for the second part.", by: "Head of infrastructure at a regional insurer" },
          { h: "Habits move with you" },
          { p: "Teams carry their old ways of working into the new platform. If a release needed a change board and a weekend window before, it often still does, even when the platform can ship a small change safely in minutes. If capacity was bought for the peak in the old data center, it is still sized for the peak in the cloud. The platform has changed. The operating model has not." },
          { p: "Year two is the right time to change this, because by then the team knows the platform well enough to trust it. We look for three habits: releases small enough to roll back, capacity that follows demand, and costs each team can see for itself. Where all three are in place, the savings in the business case usually arrive. Where none are, they almost never do." },
          { figure: "station-roof", caption: "A platform outlives the project that built it. Year two decides who looks after it." },
          { h: "Ownership is the real deliverable" },
          { p: "The question we ask at the end of every migration is simple: who owns this now? Not who has access, or who is on call, but who decides what the platform should become next year, and who pays for it. In the migrations that went well, the answer was a small internal platform team with its own budget and roadmap. In the ones that struggled, the answer was a shared mailbox." },
          { p: "That is why we plan the handover from the first week, not the last. The people who will run the platform sit in the migration team. They make some of the decisions, and some of the mistakes, while we are still there to help put them right." },
          { h: "What to do in year two" },
          {
            list: [
              "Name one person accountable for cloud spend, with a weekly report by team and the authority to switch things off.",
              "Finish decommissioning: list every old system, give each a date and an owner, and publish the list.",
              "Check every commitment and reserved capacity purchase against what you now actually run.",
              "Move to small, reversible releases, and retire the change windows the platform no longer needs.",
              "Fund the platform team as a product, with a budget and a roadmap, not as a cost center that answers tickets.",
            ],
          },
          { p: "None of this is glamorous, which is partly why it gets skipped. The first year of a migration buys an organization the chance to work differently. The second year is when it either takes that chance or pays the same costs in a new place." },
        ],
      },
      {
        type: "stats",
        tone: "paper",
        eyebrow: "The numbers",
        heading: "What year two looks like",
        items: [
          { value: "23%", label: "Average overspend against the business case in months 13 to 24." },
          { value: "1 in 3", label: "Systems due for retirement still running 18 months after their replacement went live." },
          { value: "14 months", label: "Median time to close the old estate after the last workload moved." },
          { value: "2.4x", label: "How much more likely a migration was to meet its business case with a funded platform team in place." },
        ],
        source: "KIASA review of 26 cloud migrations, 2021 to 2026.",
      },
      {
        type: "steps",
        eyebrow: "A plan",
        heading: "The second year, quarter by quarter",
        intro: "The order we suggest to clients in the twelve months after the last workload moves.",
        items: [
          { title: "Make spend visible", text: "Tag every resource to a team, send each team its own weekly bill, and name one owner for the total." },
          { title: "Close the old estate", text: "Give every remaining legacy system a retirement date and an owner. Publish the list and review it monthly." },
          { title: "Change the release habit", text: "Move to small, reversible releases and retire the change windows that only existed for the old platform." },
          { title: "Fund the platform as a product", text: "Give the platform team a budget, a roadmap and internal customers it answers to." },
        ],
      },
      {
        type: "quote",
        text: "The first year moved our systems. The second year moved our habits. That was the year the savings in the business case finally showed up.",
        name: "Rafael Duarte",
        role: "Chief Information Officer, Halden Mutual",
        image: "bridge-cables",
      },
      {
        type: "people",
        eyebrow: "Authors",
        heading: "Who wrote this",
        items: [
          { name: "Mira Castell", role: "Partner, Cloud and Platform Engineering", bio: "Mira has led cloud migrations for insurers, clinics and utilities, and stays on for the second year when clients let her." },
          { name: "Bruno Teixeira", role: "Principal Engineer, Cloud Operations", bio: "Tomás builds the cost reporting and release tooling that platform teams inherit after a migration." },
          { name: "Daniel Okafor", role: "Chief Delivery Officer", bio: "Daniel led the review of the 26 migrations behind this piece." },
        ],
      },
      {
        type: "cards",
        eyebrow: "Related",
        heading: "Keep reading",
        cta: allInsights,
        items: [read.maintenance, read.pulse, read.halden, read.green],
      },
      {
        type: "cta",
        heading: "Planning the second year of your migration?",
        text: "We will review your cloud spend, your remaining legacy estate and your platform team's remit, and give you a costed plan for the next twelve months.",
        cta: talk,
        secondary: { label: "See Cloud and Platform Engineering", href: "/what-we-do/capabilities/cloud-and-platform-engineering" },
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/insights/the-maintenance-dividend",
    title: "The maintenance dividend",
    section: "Research report",
    summary: "We asked 140 engineering leaders where their budgets go. On average, 61% is spent keeping existing systems running. The best performers spend half that, and reinvest the rest.",
    blocks: [
      {
        type: "hero",
        variant: "article",
        eyebrow: "Research report",
        title: "The maintenance dividend",
        lead: "We asked 140 engineering leaders where their budgets go. On average, 61% is spent keeping existing systems running. The best performers spend half that, and reinvest the rest.",
        image: "leaf-dew",
        meta: ["August 27, 2026", "32 page report", "By Aiko Tanaka, Osagie Bakare and Daniel Okafor"],
      },
      {
        type: "intro",
        eyebrow: "About the research",
        heading: "Where the engineering budget actually goes",
        text: "Every technology leader knows that running existing systems costs money. Few know how much. We asked 140 engineering leaders to split last year's budget between keeping systems running and changing them. The average answer was 61% on running. The best performers spent half that.",
        body: [
          "We interviewed and surveyed leaders at organizations of 500 to 15,000 people, in eight industries and nine countries, between April and June 2026. Where leaders shared budget documents, 58 of the 140, we checked their answers against them. Self-reported figures were, on average, four points too optimistic.",
          "We call the difference between the average and the best the maintenance dividend: the money and time a team gets back when its systems are cheaper to keep. This report sets out where it comes from and how the top performers spend it.",
        ],
      },
      {
        type: "stats",
        eyebrow: "The headline numbers",
        heading: "Most of the budget is spent standing still",
        items: [
          { value: "61%", label: "Average share of the engineering budget spent keeping existing systems running." },
          { value: "31%", label: "The same share for the top fifth of organizations: half the average." },
          { value: "78%", label: "The same share for the bottom fifth, leaving little for anything new." },
          { value: "2.6x", label: "How often the top fifth release changes, compared with everyone else." },
        ],
        source: "KIASA, The maintenance dividend 2026. Survey of 140 engineering leaders, April to June 2026.",
      },
      {
        type: "prose",
        aside: {
          heading: "In brief",
          points: [
            "The average organization spends 61% of its engineering budget on keeping systems running.",
            "The top fifth spend 31%, and put most of the difference into new work.",
            "System age predicts cost far less than ownership, test automation and release size.",
            "Large rewrites often raise maintenance costs for years. Steady replacement does better.",
          ],
        },
        items: [
          { h: "Why the number matters" },
          { p: "A budget that is 61% maintenance is not a failure. Systems need patching, licenses need renewing and people need support. But every point spent on standing still is a point not spent on what the business asked for this year. In our interviews, leaders in the bottom fifth described their roadmaps as wish lists. Leaders in the top fifth described them as commitments." },
          { p: "The gap is large and it compounds. A team that spends 78% on running has 22% for change. A team that spends 31% has 69%. Over three years, the second team can deliver roughly three times as much new work on the same budget, and it tends to spend part of that on making its systems cheaper still." },
          { stat: "3x", label: "The new work the top fifth can fund over three years, compared with the bottom fifth, on the same budget." },
          { h: "Age is not the problem" },
          { p: "We expected old systems to be the expensive ones. They are, a little. But when we compared systems of similar size, age explained less than a tenth of the difference in running cost. Three other things explained far more: whether the system had a named owner, how much of its testing was automated, and how large its typical release was." },
          { p: "Systems with no clear owner cost 1.9 times as much to run as owned systems of the same size and age. Nobody fixes the root cause of a problem in a system nobody owns. The same incident is handled again and again, by whoever is on call." },
          { quote: "We had a twenty-year-old billing system that was cheap to run and a three-year-old portal that was a constant fire. The difference was that one had an owner who cared.", by: "Engineering director at a telecommunications operator" },
          { h: "The trap of the big rewrite" },
          { p: "Many leaders told us they plan to cut maintenance by rewriting their largest system from scratch. Our data suggests caution. Of the leaders whose organizations completed a full rewrite in the last five years, 41% now spend more on maintenance than before. A rewrite resets ownership, test coverage and know-how to zero, and builds them back slowly." },
          { p: "The organizations that cut their maintenance share most did it steadily. They replaced one part at a time behind stable interfaces, retired what they replaced, and paid for the next step with the savings from the last." },
          { figure: "workbench", caption: "The top fifth treat maintenance as a craft: small, regular work on the tools they depend on." },
          { h: "Where the dividend goes" },
          { p: "The top fifth do not bank their savings. On average they reinvest 72% of what they free up in new product work, and most of the rest in further simplification. Few of them describe this as a strategy. It is a habit: every quarter, some of the time a team gets back is spent on making next quarter cheaper." },
          { h: "Where to start" },
          {
            list: [
              "Measure the split honestly, by system, using budget data rather than estimates.",
              "Give every system a named owner with the authority to fix root causes.",
              "Automate the regression tests on your five most-changed systems first.",
              "Shrink releases until a bad one can be rolled back in minutes.",
              "Agree in advance where the freed budget will go, so it is not quietly absorbed.",
            ],
          },
        ],
      },
      {
        type: "features",
        tone: "paper",
        numbered: true,
        eyebrow: "The top fifth",
        heading: "Four practices of the teams that spend least on standing still",
        items: [
          { title: "Every system has an owner", text: "A named person who can change it, decide its future and fix the cause of a problem, not just the symptom." },
          { title: "Tests run themselves", text: "Teams with most of their regression testing automated spent 18 points less of their budget on maintenance." },
          { title: "Releases are small", text: "A change small enough to roll back in minutes is cheap to make and cheap to undo. The top fifth release 2.6 times as often." },
          { title: "Retirement is planned", text: "Every new system arrives with a date for retiring what it replaces, and the date is kept." },
        ],
      },
      {
        type: "accordion",
        eyebrow: "Key findings",
        heading: "Five findings from the 2026 study",
        items: [
          {
            title: "Most budgets are spent standing still",
            body: [
              "Across 140 organizations, 61% of the engineering budget went on keeping existing systems running. Leaders in insurance and the public sector reported the highest shares; software companies the lowest.",
              "Only one leader in five said the split had improved in the last two years.",
            ],
            stat: { value: "61%", label: "of the average budget goes on running existing systems" },
          },
          {
            title: "Ownership matters more than age",
            body: ["Systems without a named owner cost 1.9 times as much to run as owned systems of similar size and age. Age on its own explained less than a tenth of the difference in running cost."],
            stat: { value: "1.9x", label: "running cost of systems without a named owner" },
          },
          {
            title: "Automated testing pays for itself first",
            body: [
              "Teams that automated most of their regression testing spent 18 points less of their budget on maintenance. It was the single strongest predictor in the study.",
              "Most said the investment paid back within a year.",
            ],
            stat: { value: "18 pts", label: "lower maintenance share with mostly automated testing" },
          },
          {
            title: "Big rewrites rarely reduce the bill",
            body: ["Of the organizations that completed a full rewrite of a major system in the last five years, 41% now spend more on maintenance than before. Steady, part-by-part replacement did better in every industry we studied."],
            stat: { value: "41%", label: "of rewrites were followed by higher maintenance costs" },
          },
          {
            title: "The dividend is reinvested, not banked",
            body: ["The top fifth reinvested 72% of the budget they freed in new product work. The rest went mostly on further simplification, which is why their advantage grows each year."],
            stat: { value: "72%", label: "of freed budget reinvested in new work by the top fifth" },
          },
        ],
      },
      {
        type: "people",
        eyebrow: "Authors",
        heading: "The research team",
        items: [
          { name: "Aiko Tanaka", role: "Director of Research", bio: "Aiko runs KIASA's research programs and designed the survey behind this report." },
          { name: "Osagie Bakare", role: "Partner, Application Modernization", bio: "Samuel leads our work replacing core systems one part at a time." },
          { name: "Daniel Okafor", role: "Chief Delivery Officer", bio: "Daniel is responsible for how KIASA delivers and hands over every engagement." },
        ],
      },
      {
        type: "cards",
        eyebrow: "Related",
        heading: "Keep reading",
        cta: allInsights,
        items: [read.secondYear, read.pulse, read.security, read.halden],
      },
      {
        type: "cta",
        heading: "Find your own maintenance dividend",
        text: "In two weeks we measure where your engineering budget goes, system by system, and show you which changes would free the most of it.",
        cta: talk,
        secondary: { label: "Read the news release", href: "/newsroom/maintenance-dividend-research" },
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/insights/ai-in-the-back-office",
    title: "AI in the back office: where the first real savings are showing up",
    section: "Research report",
    summary: "Forget the demos. Across 60 finance, claims and supply teams, the returns so far come from four unglamorous tasks. We name them, with numbers.",
    blocks: [
      {
        type: "hero",
        variant: "article",
        eyebrow: "Research report",
        title: "AI in the back office: where the first real savings are showing up",
        lead: "Forget the demos. Across 60 finance, claims and supply teams, the returns so far come from four unglamorous tasks. We name them, with numbers.",
        image: "desk-above",
        meta: ["July 9, 2026", "24 page report", "By Ravi Menon, Ilse Kramer and Samira Haddadi"],
      },
      {
        type: "intro",
        eyebrow: "About the research",
        heading: "Sixty teams, measured before and after",
        text: "Between October 2025 and May 2026 we studied 60 back-office teams that had put AI to work: 24 in finance, 21 in claims and 15 in supply. We measured hours, error rates and cost before and after. 41 teams saved measurable time or money. Almost all of it came from four tasks.",
        body: [
          "The teams sat in 33 mid-size organizations in insurance, banking, retail, logistics and manufacturing. Each had used AI in daily work for at least four months. We took our baselines from the teams' own work logs, not from vendor estimates.",
          "None of the four tasks will appear in a keynote. They are the work that fills a back-office day: reading documents, sending work to the right place, explaining why numbers do not match, and writing the routine reply.",
        ],
      },
      {
        type: "stats",
        eyebrow: "The headline numbers",
        heading: "Real savings, in a narrow band of work",
        items: [
          { value: "41 of 60", label: "Teams that saved measurable time or money after four months or more." },
          { value: "86%", label: "Share of the measured savings that came from just four tasks." },
          { value: "7 months", label: "Median time to pay back the cost of building and running the tool." },
          { value: "19", label: "Teams that saved nothing measurable. Most had automated a decision, not a task." },
        ],
        source: "KIASA field study of 60 back-office teams, October 2025 to May 2026.",
      },
      {
        type: "prose",
        aside: {
          heading: "In brief",
          points: [
            "41 of 60 teams saved measurable time or money; 86% of the savings came from four tasks.",
            "The four: reading documents, routing work, explaining reconciliation breaks, drafting routine replies.",
            "Every successful team kept a person reviewing the output before it left the building.",
            "The teams that saved nothing tried to automate decisions, or never measured a baseline.",
          ],
        },
        items: [
          { h: "1. Reading documents that arrive in a hundred formats" },
          { p: "Invoices, claim forms, delivery notes and medical reports arrive as scans, photos and attachments in every layout imaginable. Before AI, a person keyed the important fields into a system. In the 22 teams that automated this, a model now reads the document, fills the fields and flags the ones it is unsure of. People check the flags, not the whole document." },
          { stat: "44%", label: "Average reduction in handling time per document across the 22 teams that automated document reading." },
          { h: "2. Sending work to the right queue" },
          { p: "Claims, supplier queries and customer emails need to reach the right team the first time. Misrouted work waits, then waits again. Teams that used a model to classify incoming work and suggest a queue cut misrouting from 14% to 3% of cases. The saving is not only the minutes of sorting, but the days a misrouted case used to lose." },
          { h: "3. Explaining why the numbers do not match" },
          { p: "Reconciliation is mostly matching, which rules already do well. The expensive part is the breaks: the items that do not match and need a person to work out why. Finance teams that used a model to propose a likely explanation for each break, with the evidence, cleared breaks 2.3 times faster. The model is often wrong, but it is wrong in a way a person can see in seconds." },
          { h: "4. Drafting the routine reply" },
          { p: "Every back office writes the same letters many times a day: a request for a missing document, a payment confirmation, a status update. Teams that let a model draft these replies from the case record, for a person to edit and send, saved an average of 5.5 hours a week per person. Nobody in the study let the model send without review." },
          { figure: "desk-flatlay", caption: "The savings were in the paperwork itself: reading it, sorting it, reconciling it and answering it." },
          { h: "What the 19 teams that saved nothing had in common" },
          {
            list: [
              "They automated a decision, such as approving a payment or a claim, rather than the work around it. Of nine teams that tried this, none kept it running.",
              "They had no baseline, so they could not show a saving even where one may have existed.",
              "They chose the most visible task, not the most frequent one.",
              "The people doing the work were not involved in designing the tool, and quietly worked around it.",
            ],
          },
          { quote: "We stopped asking what the model could decide and started asking what it could prepare. That is when the hours came back.", by: "Head of claims operations at a property insurer" },
          { h: "What it costs" },
          { p: "The median team spent the equivalent of five months of one person's salary to build its tool, and a modest monthly sum to run it. Payback came in seven months at the median. The fastest paybacks were in document reading, where volumes are high and the work is easy to measure. The slowest were in drafting, where savings are spread thinly across many people." },
        ],
      },
      {
        type: "accordion",
        eyebrow: "Key findings",
        heading: "The four tasks, and the one that did not pay",
        items: [
          {
            title: "Document reading",
            body: [
              "22 teams used a model to read incoming documents and fill in the key fields, with a person checking only the fields the model flagged.",
              "Savings were highest in accounts payable and in claims intake, where documents vary most.",
            ],
            stat: { value: "44%", label: "less handling time per document" },
          },
          {
            title: "Triage and routing",
            body: ["17 teams used a model to classify incoming work and suggest a queue. Most kept a person to confirm the suggestion for the first months, then only for low-confidence cases."],
            stat: { value: "14% to 3%", label: "share of cases sent to the wrong team" },
          },
          {
            title: "Reconciliation breaks",
            body: ["11 finance teams used a model to propose an explanation for each unmatched item, with links to the evidence. Accountants accepted, edited or rejected each one."],
            stat: { value: "2.3x", label: "faster clearing of reconciliation breaks" },
          },
          {
            title: "Routine correspondence",
            body: ["19 teams used a model to draft routine replies from the case record. A person edited and sent every one."],
            stat: { value: "5.5 hrs", label: "saved per person per week" },
          },
          {
            title: "Automated decisions",
            body: ["Nine teams let a model approve payments or claims without review. All nine had stopped within six months, after errors that took longer to unwind than the tool had saved."],
            stat: { value: "0 of 9", label: "teams still letting a model decide alone" },
          },
        ],
      },
      {
        type: "quote",
        text: "The tool reads four thousand supplier invoices a week. My team reads the forty it is not sure about. That is the whole trick, and it took us a while to see it.",
        name: "Joanna Kowalczyk",
        role: "Finance Director, Fernhill Building Society",
        image: "keyboard-mug",
      },
      {
        type: "people",
        eyebrow: "Authors",
        heading: "The research team",
        items: [
          { name: "Ravi Menon", role: "Partner, Artificial Intelligence and Data", bio: "Ravi leads our work putting AI into finance, claims and supply operations." },
          { name: "Ilse Kramer", role: "Principal Data Scientist", bio: "Nadia designed the before-and-after measures used in every team in the study." },
          { name: "Samira Haddadi", role: "Research Lead", bio: "Leila ran the fieldwork across 33 organizations." },
        ],
      },
      {
        type: "cards",
        eyebrow: "Related",
        heading: "Keep reading",
        cta: allInsights,
        items: [read.pulse, read.maintenance, read.halden, read.security],
      },
      {
        type: "cta",
        heading: "Find the first task worth handing to AI",
        text: "We spend two weeks with one back-office team, measure where its hours go, and tell you which task would pay back first, if any.",
        cta: talk,
        secondary: { label: "See Artificial Intelligence and Data", href: "/what-we-do/capabilities/artificial-intelligence-and-data" },
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/insights/platform-pulse-2027",
    title: "Platform pulse: what engineering leaders will fund in 2027",
    section: "Research report",
    summary: "Budgets are flat; expectations are not. Our annual survey of 320 technology leaders shows where the money moves next year, and what is being cut to pay for it.",
    blocks: [
      {
        type: "hero",
        variant: "article",
        eyebrow: "Research report",
        title: "Platform pulse: what engineering leaders will fund in 2027",
        lead: "Budgets are flat; expectations are not. Our annual survey of 320 technology leaders shows where the money moves next year, and what is being cut to pay for it.",
        image: "glass-roof",
        meta: ["September 17, 2026", "28 page report", "By Aiko Tanaka, Lukas Hartmann and Grace Liu"],
      },
      {
        type: "intro",
        eyebrow: "About the survey",
        heading: "Flat budgets, rising expectations",
        text: "Each summer we ask technology leaders what they plan to fund next year. This year 320 answered, from organizations of 250 to 20,000 people across ten industries. The median budget for 2027 is 1% above 2026, less than inflation. Yet three in four leaders say they are expected to deliver more.",
        body: [
          "The survey ran from July 6 to August 14, 2026. Respondents were chief technology officers, chief information officers and heads of engineering. This is the fourth edition of Platform pulse, so most questions can be compared with the three before it.",
          "The answer to flat budgets is not a single big bet. It is a steady movement of money from things that are bought to things that are built and owned, and from experiments to systems in daily use.",
        ],
      },
      {
        type: "stats",
        eyebrow: "The headline numbers",
        heading: "Where 2027 is heading",
        items: [
          { value: "+1%", label: "Median planned change in technology budgets for 2027, below inflation." },
          { value: "74%", label: "Leaders expected to deliver more next year with the same budget or less." },
          { value: "58%", label: "Leaders who will increase spending on internal platforms and developer tooling." },
          { value: "64%", label: "Leaders funding at least one AI system in daily use in 2027, up from 29% this year." },
        ],
        source: "KIASA, Platform pulse 2027. Survey of 320 technology leaders, July to August 2026.",
      },
      {
        type: "prose",
        aside: {
          heading: "In brief",
          points: [
            "Median budgets rise 1% in 2027; three in four leaders must still deliver more.",
            "Money moves into internal platforms, AI in daily use, security and data quality.",
            "It comes out of overlapping licenses, contractors, on-premises hardware and pilots with no path to production.",
            "Leaders who measure what they run expect to cut less and protect more.",
          ],
        },
        items: [
          { h: "Flat is the new growth" },
          { p: "For the second year running, most leaders will not get more money. The median plan is 1% higher than 2026, and one leader in four expects a cut. What has changed is the tone. In 2025, leaders described flat budgets as a pause. This year they describe them as normal, and they are planning around them rather than waiting them out." },
          { h: "Where the money moves" },
          { p: "Four areas will grow at the expense of almost everything else. The largest is internal platforms: the shared tools, pipelines and environments that let product teams ship without waiting. 58% of leaders will spend more on them in 2027. They see a platform as the way to get more out of the same engineers." },
          {
            list: [
              "Internal platforms and developer tooling: 58% will increase spending.",
              "AI in daily use, rather than in pilots: 64% will fund at least one production system.",
              "Security: 71% call it the one budget line they will not cut.",
              "Data quality and ownership: 49% will increase spending, often to support AI.",
            ],
          },
          { stat: "71%", label: "Leaders who name security as the one budget line they will protect whatever happens." },
          { h: "What is being cut to pay for it" },
          { p: "Every increase is paid for somewhere. The largest single source is overlapping software licenses: 52% of leaders plan to consolidate tools that do the same job. Next come on-premises hardware, which 44% will not renew, and contractors, which 37% will reduce. The most telling cut is to experiments: 46% will stop funding AI pilots that have no plan to reach daily use." },
          { quote: "We have eleven pilots and two systems people actually use. Next year we fund the two and finish three more. The rest stop.", by: "Chief information officer at a logistics company" },
          { h: "AI moves from pilot to payroll" },
          { p: "In 2026, 29% of leaders had an AI system in daily use. For 2027, 64% plan to. The money for this is not new. It comes from pilots that are being stopped and from the licenses being consolidated. Leaders told us the hardest part is not the model but the data underneath it, which is why data quality appears among the rising budgets for the first time." },
          { figure: "steel-tower", caption: "Leaders are funding what holds the rest up: platforms, security and data." },
          { h: "The measurement gap" },
          { p: "Leaders who could say how much they spend running each system, about a third of the sample, expected to cut 40% less from their 2027 plans than those who could not. Knowing what you run makes it easier to defend what you need and to find what you do not." },
          { h: "What this means for your 2027 plan" },
          {
            list: [
              "Expect to fund growth by stopping things, and decide what to stop before the budget round, not during it.",
              "Treat your internal platform as a product with customers, so its value can be shown.",
              "Fund only the AI work that has a path to daily use and an owner on the business side.",
              "Measure running costs by system now, so next year's conversation starts from facts.",
            ],
          },
        ],
      },
      {
        type: "accordion",
        eyebrow: "Key findings",
        heading: "Six findings from Platform pulse 2027",
        items: [
          {
            title: "Budgets are flat for a second year",
            body: ["The median planned change for 2027 is +1%. One leader in four expects a cut; one in eight expects an increase of more than 5%."],
            stat: { value: "+1%", label: "median planned budget change" },
          },
          {
            title: "Platforms are the top area for growth",
            body: ["58% of leaders will increase spending on internal platforms and developer tooling, up from 44% a year ago. Leaders at organizations with fewer than 1,000 people are the most likely to buy this as a managed service."],
            stat: { value: "58%", label: "will spend more on internal platforms" },
          },
          {
            title: "AI is moving into daily use",
            body: ["64% of leaders will fund at least one AI system in daily use in 2027, compared with 29% in 2026. Most name finance, customer service or document handling as the first area."],
            stat: { value: "64%", label: "will run AI in daily use in 2027" },
          },
          {
            title: "Security is protected",
            body: ["71% of leaders named security as the one line they would not cut. Of those, most plan to spend more on fixing known weaknesses and less on new tools."],
            stat: { value: "71%", label: "will protect their security budget" },
          },
          {
            title: "Licenses pay for most of it",
            body: ["52% plan to consolidate overlapping software. On average, leaders expect to retire one tool in five of those they pay for today."],
            stat: { value: "52%", label: "will consolidate overlapping licenses" },
          },
          {
            title: "Pilots without a path are ending",
            body: ["46% will stop funding AI pilots with no plan to reach daily use. Leaders described a fatigue with pilots in their boards that was not there a year ago."],
            stat: { value: "46%", label: "will stop pilots with no route to production" },
          },
        ],
      },
      {
        type: "steps",
        tone: "paper",
        eyebrow: "Before you sign off",
        heading: "Five questions for your 2027 budget",
        items: [
          { title: "What will we stop?", text: "Name the tools, contracts and pilots that end next year, and what each one frees." },
          { title: "What does each system cost to run?", text: "If you cannot answer by system, make measuring it the first item of 2027." },
          { title: "Who are the platform's customers?", text: "List the teams your platform serves and what each one needs from it next year." },
          { title: "Which AI work reaches daily use?", text: "Fund work with a business owner and a date for going live. Pause the rest." },
          { title: "What security debt will we repay?", text: "Set aside a fixed share of capacity to fix known weaknesses, not only to buy new tools." },
        ],
      },
      {
        type: "people",
        eyebrow: "Authors",
        heading: "The research team",
        items: [
          { name: "Aiko Tanaka", role: "Director of Research", bio: "Aiko has run Platform pulse since its first edition in 2023." },
          { name: "Lukas Hartmann", role: "Partner, Strategy and Advisory", bio: "Jonas helps technology leaders cost and sequence their plans before anything is built." },
          { name: "Grace Liu", role: "Senior Research Analyst", bio: "Grace led the analysis and the year-on-year comparisons in this edition." },
        ],
      },
      {
        type: "cards",
        eyebrow: "Related",
        heading: "Keep reading",
        cta: allInsights,
        items: [read.maintenance, read.backOffice, read.secondYear, read.canopy],
      },
      {
        type: "cta",
        heading: "Test your 2027 plan against your peers",
        text: "We will compare your budget with the 320 in this year's survey and show you where you differ, and whether it matters.",
        cta: talk,
        secondary: { label: "See Strategy and Advisory", href: "/what-we-do/capabilities/strategy-and-advisory" },
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/insights/green-software-is-good-software",
    title: "Green software is mostly just good software",
    section: "Perspective",
    summary: "The code that wastes the least energy is usually the code that is simplest to run. A practical look at carbon as an engineering measure.",
    blocks: [
      {
        type: "hero",
        variant: "article",
        eyebrow: "Perspective",
        title: "Green software is mostly just good software",
        lead: "The code that wastes the least energy is usually the code that is simplest to run. A practical look at carbon as an engineering measure.",
        image: "young-leaves",
        meta: ["June 18, 2026", "7 minute read", "By Oluwaseun Bakare and Freya Nilsson"],
      },
      {
        type: "prose",
        aside: {
          heading: "In brief",
          points: [
            "Software uses energy when it computes, stores and moves data. Most waste is in work nobody asked for.",
            "Idle environments, oversized servers, chatty services and data kept forever account for most of it.",
            "Treat carbon like latency: a number per transaction that a team can see and improve.",
            "Where green and good disagree, as with resilience, decide openly rather than by default.",
          ],
        },
        items: [
          { p: "Green software has a reputation for being a specialist field, with its own tools, its own vocabulary and a separate budget. In our work it is mostly something simpler. The software that uses the least energy is nearly always the software that does the least unnecessary work. And software that does the least unnecessary work is cheaper, faster and easier to run." },
          { p: "That is good news for anyone who has been asked to cut emissions and costs in the same year. In most estates the two point the same way." },
          { h: "Where the energy goes" },
          { p: "Software uses energy in three ways: when it computes, when it stores data and when it moves data across a network. In the estates we have measured, the largest share of that energy goes on work that nobody asked for. Servers that wait. Copies of data nobody reads. Services that ask each other the same question a thousand times a minute." },
          {
            list: [
              "Idle environments: test and staging systems left running nights and weekends.",
              "Oversized servers: capacity bought for a peak that comes twice a year.",
              "Chatty services: calls between systems that could be batched, cached or removed.",
              "Data kept forever: logs and copies stored in fast storage long after anyone needs them.",
            ],
          },
          { stat: "70%", label: "Typical share of hours in which non-production environments sat idle, in the estates we measured." },
          { h: "Start with the hours nobody uses" },
          { p: "The quickest saving is almost always the same. Non-production environments run around the clock, but people use them during working hours. Switching them off at night and at weekends cut compute hours by 38% at one manufacturing client, with no change to a single line of application code. The cloud bill fell by a similar share." },
          { p: "The next saving is usually in the code. At a regional retailer, one product search query was responsible for a fifth of the database's load. Rewriting it took two days. CPU use on the database fell by 60% and the search page loaded in half the time. Nobody had looked, because the page worked." },
          { quote: "We went looking for carbon and found performance problems. Fixing them did both jobs at once.", by: "Head of platform at a manufacturing company" },
          { h: "Carbon as an engineering measure" },
          { p: "Teams improve what they can see. Latency became a habit when every team had a dashboard showing it per request. Carbon can work the same way. We help teams estimate the energy and emissions per transaction, per order or per report, and put that number next to latency and cost. It does not need to be precise to be useful. It needs to move when the code changes." },
          { p: "Two choices outside the code matter too. Where a workload runs changes its footprint, because grids vary widely in how much carbon each unit of electricity carries. When it runs matters for work that can wait: a nightly batch can often move to the hours when the grid is cleanest, at no cost to anyone." },
          { figure: "wheat", caption: "Most of the gain comes from doing less: fewer idle hours, fewer copies, fewer calls." },
          { h: "Where green and good disagree" },
          { p: "Not every choice points the same way. Running a system in two regions for resilience doubles part of its footprint. Keeping data for regulators means storing it. These are good decisions, and we would not reverse them. The point is to make them on purpose, knowing the cost, rather than inheriting them from a default nobody chose." },
          { p: "Green software is not a separate discipline to bolt on. It is a reason to do the things good engineering teams already know they should: measure, simplify, switch off what is not used, and look at the slow query." },
        ],
      },
      {
        type: "stats",
        tone: "paper",
        eyebrow: "From our client work",
        heading: "What simple changes saved",
        items: [
          { value: "38%", label: "Fewer compute hours from switching off non-production environments outside working hours." },
          { value: "60%", label: "Less database CPU after rewriting a single search query." },
          { value: "70%", label: "Typical idle share of non-production hours before any change." },
          { value: "2 days", label: "Engineering time for the query fix that halved a page's load time." },
        ],
        source: "KIASA client work, 2024 to 2026. Figures are from individual engagements and will vary by estate.",
      },
      {
        type: "steps",
        eyebrow: "Where to start",
        heading: "Four steps for this quarter",
        items: [
          { title: "Schedule the idle hours", text: "Switch off non-production environments at night and at weekends. Measure the change in hours and cost." },
          { title: "Find the heaviest query", text: "Look at the database and service calls that use the most resources, and fix the worst one." },
          { title: "Tidy the storage", text: "Set retention rules for logs and copies, and move what must be kept to cheaper, colder storage." },
          { title: "Show the number", text: "Put an estimate of energy per transaction on the team dashboard, next to latency and cost." },
        ],
      },
      {
        type: "quote",
        text: "Our engineers did not need persuading once they saw the numbers on their own dashboard. Carbon per order went down, and so did the bill.",
        name: "Ilse Vermeulen",
        role: "Head of Platform, Calder Works",
        image: "field-tree",
      },
      {
        type: "people",
        eyebrow: "Authors",
        heading: "Who wrote this",
        items: [
          { name: "Oluwaseun Bakare", role: "Lead, Green Software", bio: "Oluwaseun measures and cuts the energy cost of client estates, starting with the parts nobody uses." },
          { name: "Freya Nilsson", role: "Staff Engineer", bio: "Freya builds the per-transaction carbon estimates our teams put on their dashboards." },
          { name: "Mira Castell", role: "Partner, Cloud and Platform Engineering", bio: "Mira reviewed the client examples in this piece." },
        ],
      },
      {
        type: "cards",
        eyebrow: "Related",
        heading: "Keep reading",
        cta: allInsights,
        items: [read.secondYear, read.maintenance, read.varda, read.pulse],
      },
      {
        type: "cta",
        heading: "Measure the carbon cost of your software",
        text: "We will estimate the energy and emissions of your largest systems, and show you the changes that cut both carbon and cost.",
        cta: talk,
        secondary: { label: "See Green Software", href: "/what-we-do/capabilities/green-software" },
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    href: "/insights/security-debt",
    title: "Security debt: the quiet risk on the balance sheet",
    section: "Research report",
    summary: "Unpatched systems behave like unpaid loans: the interest compounds. A way to measure the exposure, and a plan for paying it down.",
    blocks: [
      {
        type: "hero",
        variant: "article",
        eyebrow: "Research report",
        title: "Security debt: the quiet risk on the balance sheet",
        lead: "Unpatched systems behave like unpaid loans: the interest compounds. A way to measure the exposure, and a plan for paying it down.",
        image: "leaf-drop",
        meta: ["May 21, 2026", "20 page report", "By Hamid Rezaei, Clara Mendes and Aiko Tanaka"],
      },
      {
        type: "intro",
        eyebrow: "About the research",
        heading: "Known weaknesses, left unpaid",
        text: "Security debt is the backlog of known weaknesses an organization has chosen, or forgotten, not to fix. Like financial debt it carries interest: every month a weakness stays open, it becomes more expensive to fix and more likely to be used against you.",
        body: [
          "We analyzed 52 security assessments KIASA carried out between 2023 and 2026, at organizations of 300 to 12,000 people, and interviewed 30 security leaders about how they decide what to fix and what to leave.",
          "Most organizations track their weaknesses as a list. Few treat them as a liability with a size, an owner and a repayment plan. This report suggests a way to do that.",
        ],
      },
      {
        type: "stats",
        eyebrow: "The headline numbers",
        heading: "The size of the debt",
        items: [
          { value: "96 days", label: "Median time to patch a critical weakness on a system reachable from the internet." },
          { value: "38%", label: "Estates running at least one internet-facing component past the end of its vendor support." },
          { value: "3.4x", label: "Cost of fixing a weakness after a year, compared with fixing it within 30 days." },
          { value: "11%", label: "Share of known weaknesses that accounted for 80% of the measured exposure." },
        ],
        source: "KIASA analysis of 52 security assessments, 2023 to 2026, and interviews with 30 security leaders.",
      },
      {
        type: "prose",
        aside: {
          heading: "In brief",
          points: [
            "Known weaknesses behave like debt: the cost of fixing them grows the longer they wait.",
            "A weakness fixed after a year costs 3.4 times as much as one fixed within 30 days.",
            "A few weaknesses carry most of the risk: 11% of them account for 80% of exposure.",
            "Set aside a fixed share of capacity to repay the debt, and stop new borrowing at the source.",
          ],
        },
        items: [
          { h: "A list is not a liability" },
          { p: "Every organization we assessed had a list of known weaknesses. The median list ran to more than 1,400 items. What almost none had was a way to say how much risk the list represented in total, whether it was growing or shrinking, and who was responsible for bringing it down. A list of 1,400 items does not get discussed by a board. A liability with a number does." },
          { h: "How the interest compounds" },
          { p: "A weakness left open does not stay the same size. The software around it moves on, so the eventual fix touches more. The people who understood the system leave. The vendor ends support, and a simple patch becomes an upgrade project. Meanwhile the weakness becomes better known to attackers, and the tools that exploit it become cheaper." },
          { stat: "3.4x", label: "How much more it cost to fix a weakness after twelve months than within 30 days, across the assessments we analyzed." },
          { p: "Compensating controls, the firewall rule or extra monitoring added instead of a fix, are the minimum payments of security debt. They keep the account in good standing but do not reduce the balance, and each one adds to what the operations team must remember." },
          { quote: "We were paying interest on decisions nobody remembered making. Once we put a number on it, the conversation with the board changed in a single meeting.", by: "Chief information security officer at a healthcare provider" },
          { h: "Measuring the debt" },
          { p: "We score each known weakness on three things: how severe it is, how exposed the system is, and how long it has been open. Multiplied together and summed across the estate, they give a single figure that can be tracked month by month. It is not a prediction of loss. It is a measure of how much risk is being carried, and whether it is going up or down." },
          { p: "The figure is lopsided. In the median estate, 11% of weaknesses accounted for 80% of the score. Most were on internet-facing systems, and many were on components past their vendor's end of support. That is good news: a small, well-chosen effort removes most of the exposure." },
          { figure: "bridge-below", caption: "Security debt sits underneath working systems, out of sight until it is not." },
          { h: "Paying it down" },
          { p: "The organizations that reduced their debt fastest did not run large one-off programs. They set aside a fixed share of engineering capacity, typically 10 to 15%, for repayment every sprint, and they stopped adding new debt by making security fixes part of the definition of done." },
          {
            list: [
              "Make an inventory of every system, its owner and its exposure to the internet.",
              "Score the debt and report it monthly, by system and by owner.",
              "Repay the most exposed 11% first, starting with anything past end of support.",
              "Reserve a fixed share of every team's capacity for repayment.",
              "Stop new borrowing: no release ships with a known critical weakness.",
            ],
          },
          { p: "Security debt will never reach zero, and it does not have to. The aim is a balance that is known, owned and falling, in the same way a sensible business manages any other liability." },
        ],
      },
      {
        type: "accordion",
        eyebrow: "Key findings",
        heading: "Five findings from 52 assessments",
        items: [
          {
            title: "Critical fixes take months, not days",
            body: ["The median time to patch a critical weakness on an internet-facing system was 96 days. The fastest quarter of organizations did it in under 14."],
            stat: { value: "96 days", label: "median time to patch a critical weakness" },
          },
          {
            title: "End of support is the largest single source of debt",
            body: ["38% of estates ran at least one internet-facing component that its vendor no longer supports. Each one turns routine patching into an upgrade project."],
            stat: { value: "38%", label: "of estates ran unsupported internet-facing components" },
          },
          {
            title: "Delay multiplies cost",
            body: ["Fixing a weakness after twelve months cost 3.4 times as much as fixing it within 30 days, measured in engineering hours, testing and change effort."],
            stat: { value: "3.4x", label: "cost of fixing after a year" },
          },
          {
            title: "A few weaknesses carry most of the risk",
            body: ["In the median estate, 11% of known weaknesses accounted for 80% of the exposure score. Fixing them first reduced measured exposure fastest."],
            stat: { value: "11%", label: "of weaknesses carried 80% of exposure" },
          },
          {
            title: "Steady repayment beats big programs",
            body: ["Organizations that reserved 10 to 15% of capacity for repayment halved their exposure score within a year. One-off programs cut it faster at first, then let it grow back."],
            stat: { value: "50%", label: "lower exposure within a year with steady repayment" },
          },
        ],
      },
      {
        type: "steps",
        tone: "paper",
        eyebrow: "A repayment plan",
        heading: "Five steps to pay down security debt",
        items: [
          { title: "Take stock", text: "List every system, its owner and whether it can be reached from the internet." },
          { title: "Put a number on it", text: "Score each weakness by severity, exposure and age, and add them up." },
          { title: "Repay the expensive debt first", text: "Fix the most exposed tenth, starting with components past end of support." },
          { title: "Budget for repayment", text: "Reserve 10 to 15% of each team's capacity for fixes, every sprint." },
          { title: "Stop new borrowing", text: "Make security fixes part of the definition of done, so new releases add no debt." },
        ],
      },
      {
        type: "people",
        eyebrow: "Authors",
        heading: "The research team",
        items: [
          { name: "Hamid Rezaei", role: "Partner, Cybersecurity", bio: "Hamid leads KIASA's security assessments and the teams that fix what they find." },
          { name: "Clara Mendes", role: "Principal Security Engineer", bio: "Clara designed the exposure score used throughout this report." },
          { name: "Aiko Tanaka", role: "Director of Research", bio: "Aiko ran the interviews with 30 security leaders." },
        ],
      },
      {
        type: "cards",
        eyebrow: "Related",
        heading: "Keep reading",
        cta: allInsights,
        items: [read.maintenance, read.pulse, read.backOffice, read.tessera],
      },
      {
        type: "cta",
        heading: "Get a clear view of your security debt",
        text: "In three weeks we score your estate's known weaknesses, show you where 80% of the exposure sits, and cost a plan to pay it down.",
        cta: talk,
        secondary: { label: "See Cybersecurity", href: "/what-we-do/capabilities/cybersecurity" },
      },
    ],
  },
];
